### ISSUE TITLE
Recognition Training with Tensorflow

### ISSUE THREAD

**Issue by zahidetastan** [mindee/doctr#1006]
### Bug description

I want to use docTR for training of Recognition of Turkish language data. I have created a dataset as specified in documentation. I have also added the vocab for Turkish in vocabs.py. Turkish language consists of VOCAB['English'] + some turkish chars. For example: i, ö, ü, İ. 
Therefore, there are some Turkish special characters in the train images and json file in the dataset. When I start the training with these dataset, I get an error like the one below. As can be seen in the Target section, the entered Turkish characters are not read as in the json file. For example, capital i in "TARİH: 24.08.2021" and "NAKİT".

And this is not just a situation specific to Turkish. When I start a train for Portuguese, it similarly does not accept the dataset containing values ​​that match the characters in the VOCAB file.

![image](https://user-images.githubusercontent.com/45240849/182177873-a96a279c-457b-4c9f-b2b8-68eae80e8c81.png)

Can someone explain why I am getting this error and what has to be changed? How can I train the dataset containing some special characters?

### Code snippet to reproduce the bug

Here is my training script 
'''python references/recognition/train_tensorflow.py crnn_vgg16_bn --train_path references/doctr-train --val_path references/doctr-valid --epochs 5 --vocab turkish'''

### Error traceback

'''
Namespace(arch='crnn_vgg16_bn', train_path='references/doctr-train', val_path='references/doctr-valid', train_samples=1000, val_samples=20, font='FreeMono.ttf,FreeSans.ttf,FreeSerif.ttf', min_chars=1, max_chars=12, name=None, epochs=5, batch_size=64, input_size=32, lr=0.001, workers=None, resume=None, vocab='turkish', test_only=False, show_samples=False, wb=False, push_to_hub=False, pretrained=False, amp=False, find_lr=False)
b'{\r\n    "1.png": "KDV",\r\n    "2.png": "*400,00",\r\n    "3.png": "TAR\xc4\xb0H:24.08.2021",\r\n    "4.png": "NAK\xc4\xb0T",\r\n    "5.png": "TOPLAM",\r\n    "6.png": "Bakiye:"\r\n}'
Validation set loaded in 0.001001s (6 samples in 1 batches)
Train set loaded in 0.0009604s (6 samples in 0 batches)
TARÄ°H:24.08.2021 //for debug, it prints file content
0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~iİöÖÇçÜü // for debug it prints my turkish vocab
Traceback (most recent call last):
  File "C:\Users\x\Desktop\training-DOCTR\doctr\doctr\references\recognition\train_tensorflow.py", line 404, in <module>
    main(args)
  File "C:\Users\x\Desktop\training-DOCTR\doctr\doctr\references\recognition\train_tensorflow.py", line 330, in main
    val_loss, exact_match, partial_match = evaluate(model, val_loader, batch_transforms, val_metric)
  File "C:\Users\x\Desktop\training-DOCTR\doctr\doctr\references\recognition\train_tensorflow.py", line 115, in evaluate
    out = model(images, targets, return_preds=True, training=False)
  File "C:\Users\x\Desktop\training-DOCTR\doctr\doctr\trainvenv\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "c:\users\x\desktop\training-doctr\doctr\doctr\doctr\models\recognition\crnn\tensorflow.py", line 229, in call
    out['loss'] = self.compute_loss(logits, target)
  File "c:\users\x\desktop\training-doctr\doctr\doctr\doctr\models\recognition\crnn\tensorflow.py", line 184, in compute_loss
    gt, seq_len = self.build_target(target)
  File "c:\users\x\desktop\training-doctr\doctr\doctr\doctr\models\recognition\core.py", line 35, in build_target
    encoded = encode_sequences(
  File "c:\users\x\desktop\training-doctr\doctr\doctr\doctr\datasets\utils.py", line 153, in encode_sequences
    for idx, seq in enumerate(map(partial(encode_string, vocab=vocab), sequences)):
  File "c:\users\x\desktop\training-doctr\doctr\doctr\doctr\datasets\utils.py", line 80, in encode_string
    raise ValueError("some characters cannot be found in 'vocab'")
ValueError: Exception encountered when calling layer "crnn" (type CRNN).

some characters cannot be found in 'vocab'

Call arguments received by layer "crnn" (type CRNN):
  • x=tf.Tensor(shape=(6, 32, 128, 3), dtype=float32)
  • target=["'KDV'", "'*400,00'", "'TARÄ°H:24.08.2021'", "'NAKÄ°T'", "'TOPLAM'", "'Bakiye:'"]
  • return_model_output=False
  • return_preds=True
  • beam_width=1
  • top_paths=1
  • kwargs={'training': 'False'}
'''

### Environment

--

### Deep Learning backend

is_tf_available: True
is_torch_available: False

**Comment by frgfm** [comment]
Hello @zahidetastan :wave:

Sorry about this, let's try to help you!
Do you have a fork with a branch that has your modifications by any chance?

My best guess is that the string encoding doesn't work with some Turkish characters  (or simply that the font doesn't support this character) :thinking: 
So let's try to check this with 3 steps:
1. Check whether the string encoding is a problem
To do so, let's see what this piece of code outputs:
```python
from doctr.datasets.utils import encode_sequences
encode_sequences(["NAKİT"], vocab=<YOUR_TURKISH_VOCAB>)
```

2. Check if the text image generation (or the font) is a problem 
For this, could you try to run this piece of code and post the resulting image please?
```python
import matplotlib.pyplot as plt
from doctr.datasets.generator.base import synthesize_text_img
plt.imshow(synthesize_text_img("NAKİT")); plt.show()
```

3. Check whether the target generation is a problem
```python
from doctr.datasets import CharacterGenerator, WordGenerator
char_ds = CharacterGenerator("<YOUR_TURKISH_VOCAB>")
print(list(map(char_ds.vocab.__getitem__, [sample[1] for sample in char_ds._data])))
word_ds = WordGenerator("<YOUR_TURKISH_VOCAB>")
print(word_ds._generate_string(100, 200))
```

Let me know if you run into any trouble!
Cheers :v:

**Comment by zahidetastan** [comment]
Hello,
First of all, thank you very much for your interest.

Here is my output of first checking for string encoding. 

![option1](https://user-images.githubusercontent.com/45240849/182589294-8d405397-37c6-4509-b532-e83bf40654f9.png)

And here is my output of second checking for text image generation or the font problem. I can't get any resulting image due to the error. 
![option2](https://user-images.githubusercontent.com/45240849/182589600-b304c342-421e-475e-9c63-fc9f25081119.png)
 
So our problem is CAPITAL LETTER I WITH DOT ABOVE(İ): UnicodeEncodeError: 'latin-1' codec can't encode character '\u0130' in position 3: ordinal not in range(256)

**Comment by frgfm** [comment]
Alright, this has narrowed the problem down to the image generation!
This snippet should produce the same error then:
```python
from doctr.utils.fonts import get_font

font = get_font(None, 32)
font.getsize("İ")
```

If so, I can see two options:
- normalizing the string so that the latin-1 codec can do its job
- finding a font family that includes your character

The second aspect is quite a natural one: you can't render the string if it cannot be mapped to a font family that has been installed in your environment. Both solutions shouldn't logically be implemented on docTR side, I suggest that you find a font family that allows the rendering :+1: 

Hint: you haven't specified a font family, so it loads the default, which is quite limited. But if a common font family like Arial supports this character, you could do:
```python
font = get_font("Arial.ttf", 32)
```
which should fix the problem :)

Let me know how it goes!

**Comment by khawar-islam** [comment]
Hello @frgfm I am also training a recognition model for korean language and i made three changes but still there is some problem like above.

**First changed** [Added korean language]

```
VOCABS: Dict[str, str] = {
    'digits': string.digits,
    'ascii_letters': string.ascii_letters,
    'punctuation': string.punctuation,
    'currency': '£€¥¢฿',
    'ancient_greek': 'αβγδεζηθικλμνξοπρστυφχψωΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩ',
    'arabic_letters': 'ءآأؤإئابةتثجحخدذرزسشصضطظعغـفقكلمنهوىي',
    'persian_letters': 'پچڢڤگ',
    'hindi_digits': '٠١٢٣٤٥٦٧٨٩',
    'arabic_diacritics': 'ًٌٍَُِّْ',
    'arabic_punctuation': '؟؛«»—',
    'korean':'ㄱㄴㄷㄹㅁㅂㅅㅇㅈㅊㅋㅌㅍㅎㅏㅑㅓㅕㅗㅛㅜㅠㅡㅣ'
}

VOCABS['latin'] = VOCABS['digits'] + VOCABS['ascii_letters'] + VOCABS['punctuation']
VOCABS['english'] = VOCABS['latin'] + '°' + VOCABS['currency']
VOCABS['legacy_french'] = VOCABS['latin'] + '°' + 'àâéèêëîïôùûçÀÂÉÈËÎÏÔÙÛÇ' + VOCABS['currency']
VOCABS['french'] = VOCABS['english'] + 'àâéèêëîïôùûüçÀÂÉÈÊËÎÏÔÙÛÜÇ'
VOCABS['portuguese'] = VOCABS['english'] + 'áàâãéêíïóôõúüçÁÀÂÃÉÊÍÏÓÔÕÚÜÇ'
VOCABS['spanish'] = VOCABS['english'] + 'áéíóúüñÁÉÍÓÚÜÑ' + '¡¿'
VOCABS['german'] = VOCABS['english'] + 'äöüßÄÖÜẞ'
VOCABS['arabic'] = (VOCABS['digits'] + VOCABS['hindi_digits'] + VOCABS['arabic_letters'] + VOCABS['persian_letters'] +
                    VOCABS['arabic_diacritics'] + VOCABS['arabic_punctuation'] + VOCABS['punctuation'])
VOCABS['czech'] = VOCABS['english'] + 'áčďéěíňóřšťúůýžÁČĎÉĚÍŇÓŘŠŤÚŮÝŽ'
VOCABS['vietnamese'] = (VOCABS['english'] +
                        'áàảạãăắằẳẵặâấầẩẫậéèẻẽẹêếềểễệóòỏõọôốồổộỗơớờởợỡúùủũụưứừửữựiíìỉĩịýỳỷỹỵ' +
                        'ÁÀẢẠÃĂẮẰẲẴẶÂẤẦẨẪẬÉÈẺẼẸÊẾỀỂỄỆÓÒỎÕỌÔỐỒỔỘỖƠỚỜỞỢỠÚÙỦŨỤƯỨỪỬỮỰIÍÌỈĨỊÝỲỶỸỴ')
VOCABS['korean'] = (VOCABS['digits'] + VOCABS['english'] + VOCABS['korean'])
```

**Second changed** [french to korean]

`    parser.add_argument('--vocab', type=str, default="korean", help='Vocab to be used for training')`

Training start

`python3 references/recognition/train_pytorch.py master --train_path /media/cvpr/CM_1/CM/dataset_KR/dataset/train --val_path /media/cvpr/CM_1/CM/dataset_KR/dataset/val --epochs 5 --batch_size 16`

**Comment by frgfm** [comment]
Any update @zahidetastan ? :)

**Comment by zahidetastan** [comment]
Hello @frgfm 
Finding a font family that includes Turkish character solved the error. But...
I training the model by running the push to hub part as a comment line. But I couldn't figure out where to get an output and how to use this trained model. 
Then I wanted to use the push_to_hub argument to see the trained model on the hub. In this part, I get an error about libraries.


![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/45240849/187620530-a879a66c-b05e-4834-9efe-ec9a56f1c450.png)

**Comment by felixdittrich92** [comment]
Hi @zahidetastan :wave:, i can help with this.
Are you currently on the main branch so you have forked the repo to train your model ?

**Comment by zahidetastan** [comment]
Hi @felixdittrich92 👋,
Yes I currently on main branch. And I fixed the problem about the login_to_hub error. By adding sys.path.append('.') before the importing login_to_hub line. And also there had a problem about importing doctr from venv instead of folder. I deleted the python-doctr library from my environment.
After completing the training, I have tf_model folder + config.json file. Inside the tf_model folder there is checkpoint, weights.data-00000-of-00001 and weights.index file. 
How should I proceed after this stage? 

Thanks for your all efford and help :)

**Comment by felixdittrich92** [comment]
Hi @zahidetastan :wave: ,

Pushing to hub with your own trained model:
```
from doctr.models import recognition, login_to_hub, push_to_hf_hub
login_to_hub()
my_awesome_model = recognition.crnn_vgg16_bn(pretrained=False, pretrained_backbone=False)
my_awesome_model.load_weights("path-to-your-trained-model-folder/weights")

push_to_hf_hub(my_awesome_model, model_name='doctr-crnn-vgg16-bn-turkish-v1', task='recognition', arch='crnn_vgg16_bn')  # task and arch needs to match with model so in your case it is a recognition model and the arch ist crnn_vgg16_bn    name can be free choosen
```



Loading example:
```
from doctr.io import DocumentFile
from doctr.models import ocr_predictor, from_hub
image = DocumentFile.from_images(['data/example.jpg'])
# Load a custom detection model from huggingface hub
det_model = from_hub('Felix92/doctr-tf-db-resnet50')
# Load a custom recognition model from huggingface hub
reco_model = from_hub('Felix92/doctr-tf-crnn-vgg16-bn-french')
# You can easily plug in this models to the OCR predictor
predictor = ocr_predictor(det_arch=det_model, reco_arch=reco_model)

# in your case:
predictor = ocr_predictor(reco_arch=reco_model, pretrained=True) # load pretrained text detection model and use custom reco model from hub
result = predictor(image)
```

**Comment by felixdittrich92** [comment]
Hi @zahidetastan, sry yes to init the model you should use from_hub 

ocr_predictor(reco_arch=from_hub(your model), pretrained=True)

But it seems in config.json that the vocab is empty that's weird 🤔

**Comment by zahidetastan** [comment]
Hi @felixdittrich92, 
Yes, I passed the turkish vocab in vocabs.py on my local.😅 There is no problem at that point. I will check the path again. 
Thank you for all help ✋🏻

**Comment by felixdittrich92** [comment]
@zahidetastan could you share the turkish vocab you have added ? So i can trigger a minor toy run and try to reproduce your behaviour tomorrow ^^

**Comment by felixdittrich92** [comment]
@zahidetastan let me know if i can delete the dummy model from my hub if you got all :+1:

**Comment by felixdittrich92** [comment]
Hi @zahidetastan any updates ? :)

**Comment by zahidetastan** [comment]
Hi @felixdittrich92,
The dataset I had was a very small dataset. It contained 10 pieces of data that I created by clipping from images by manuel. 
So when I used it as the recognition model, I saw some random characters as a result. That's why I found a font with Turkish characters that is CODE2000.TTF. I made a dummy train with this font. And I use an image that contains some Turkish char with font that I mentioned.  We can see the result in the below. 
What should I expect as a dummy train result? Is there something I misunderstood here?
Dummy train created 100,000 train data. Even if I create this much data and train the model with real data, will it be poorly for training? 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/45240849/189374757-45a99ac2-3dfe-4f59-9b1c-a394b3f64092.png)

**Comment by felixdittrich92** [comment]
Hi @zahidetastan 👋 nice that the hf part now works correctly 👍 
About the dataset i would suggest to fine tune the already pretrained model (on french you need only to pass --pretrained) on your real dataset (try to get as much data as possible) because the vocabs differ only in a few characters.
About training with our word generator it needs some improvements and is more about pretraining or to debug models and is currently Not a good fit to train a prod ready model 😅

**Comment by felixdittrich92** [comment]
Will convert it to a discussion looks like the main issue is solved :)
