### ISSUE TITLE
GPU inference error using db_resne50_rotation

### ISSUE THREAD

**Issue by harindercnvrg** [mindee/doctr#1020]
### Bug description

Hello, guys I am getting the following error by running the snipped of code. I don't  get the same error if I use db_resnet50 instead of db_resnet50_rotation. Help please! I am using the version 0.5.1

### Code snippet to reproduce the bug

```
from doctr.io import DocumentFile
from doctr.models import ocr_predictor
tic = time.time()
doc = DocumentFile.from_pdf("/content/file.pdf")
print(f"Number of pages: {len(doc)}")
predictor = ocr_predictor('db_resnet50_rotation','crnn_vgg16_bn',pretrained=True,assume_straight_pages=False).cuda()
result = predictor(doc)
```

### Error traceback

```
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor
```

### Environment
```
!pip install python-doctr[torch]
!sudo apt-get install fonts-freefont-ttf -y
!pip3 install --no-build-isolation -U pypdfium2==1.0.0
```
### Deep Learning backend
```
is_tf_available: False
is_torch_available: True
```

**Comment by harindercnvrg** [comment]
First, could you elaborate on "I don't get the same error if I use db_resnet50 instead of db_resnet50_rotation". What error do you get if you use that one?
Yes, please look below:

**Comment by frgfm** [comment]
Thanks for that! The traceback gave the source of the problem away: the input tensor isn't being moved to the device of the model as it should.

I'll fix this shortly then :) 
I'll let you know here when it's merged!

**Comment by felixdittrich92** [comment]
Hi @harindercnvrg should work now (on main) 👋

**Comment by minouei-kl** [comment]
Hi
I'm getting a similar error using db_resne50_rotation with version 0.7.1a0.
it is working fine with db_resne50.
Error traceback
```
Traceback (most recent call last):
  File "ocr.py", line 42, in <module>
    result = model(image)
  File "/home/minouei/miniconda3/envs/mmocr3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/minouei/miniconda3/envs/mmocr3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/minouei/Documents/models/rvl/gits/doctr/doctr/models/predictor/pytorch.py", line 117, in forward
    crops, loc_preds = self._rectify_crops(crops, loc_preds)
  File "/home/minouei/Documents/models/rvl/gits/doctr/doctr/models/predictor/base.py", line 93, in _rectify_crops
    orientations = [self.crop_orientation_predictor(page_crops) for page_crops in crops]  # type: ignore[misc]
  File "/home/minouei/Documents/models/rvl/gits/doctr/doctr/models/predictor/base.py", line 93, in <listcomp>
    orientations = [self.crop_orientation_predictor(page_crops) for page_crops in crops]  # type: ignore[misc]
  File "/home/minouei/miniconda3/envs/mmocr3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/minouei/miniconda3/envs/mmocr3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/minouei/Documents/models/rvl/gits/doctr/doctr/models/classification/predictor/pytorch.py", line 48, in forward
    predicted_batches = [self.model(batch).to(device=_device) for batch in processed_batches]
  File "/home/minouei/Documents/models/rvl/gits/doctr/doctr/models/classification/predictor/pytorch.py", line 48, in <listcomp>
    predicted_batches = [self.model(batch).to(device=_device) for batch in processed_batches]
  File "/home/minouei/miniconda3/envs/mmocr3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/minouei/miniconda3/envs/mmocr3/lib/python3.8/site-packages/torchvision/models/mobilenetv3.py", line 179, in forward
    return self._forward_impl(x)
  File "/home/minouei/miniconda3/envs/mmocr3/lib/python3.8/site-packages/torchvision/models/mobilenetv3.py", line 169, in _forward_impl
    x = self.features(x)
  File "/home/minouei/miniconda3/envs/mmocr3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/minouei/miniconda3/envs/mmocr3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/minouei/miniconda3/envs/mmocr3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/minouei/miniconda3/envs/mmocr3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/minouei/miniconda3/envs/mmocr3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/minouei/miniconda3/envs/mmocr3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/minouei/miniconda3/envs/mmocr3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 442, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor
