### ISSUE TITLE
Error in training Detection model using pytorch

### ISSUE THREAD

**Issue by dishant26** [mindee/doctr#1043]
### Bug description

I am trying to train the detection model using pytorch on my own dataset and I am getting this error.
I am using macOS.
```Can't pickle local object 'DetectionDataset.__init__.<locals>.<lambda>'```

### Code snippet to reproduce the bug

```
python references/detection/train_pytorch.py /Users/dishantpadalia/IITB/doctr_detection/train /Users/dishantpadalia/IITB/doctr_detection/val db_resnet50 --epochs 5
```

### Error traceback

```
Traceback (most recent call last):
  File "/Users/dishantpadalia/IITB/doctr/references/detection/train_pytorch.py", line 414, in <module>
    main(args)
  File "/Users/dishantpadalia/IITB/doctr/references/detection/train_pytorch.py", line 345, in main
    fit_one_epoch(model, train_loader, batch_transforms, optimizer, scheduler, mb, amp=args.amp)
  File "/Users/dishantpadalia/IITB/doctr/references/detection/train_pytorch.py", line 110, in fit_one_epoch
    for images, targets in progress_bar(train_loader, parent=mb):
  File "/Users/dishantpadalia/opt/miniconda3/envs/iitb_2/lib/python3.10/site-packages/fastprogress/fastprogress.py", line 50, in __iter__
    raise e
  File "/Users/dishantpadalia/opt/miniconda3/envs/iitb_2/lib/python3.10/site-packages/fastprogress/fastprogress.py", line 41, in __iter__
    for i,o in enumerate(self.gen):
  File "/Users/dishantpadalia/opt/miniconda3/envs/iitb_2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 444, in __iter__
    return self._get_iterator()
  File "/Users/dishantpadalia/opt/miniconda3/envs/iitb_2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 390, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/Users/dishantpadalia/opt/miniconda3/envs/iitb_2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1075, in __init__
    w.start()
  File "/Users/dishantpadalia/opt/miniconda3/envs/iitb_2/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/dishantpadalia/opt/miniconda3/envs/iitb_2/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/dishantpadalia/opt/miniconda3/envs/iitb_2/lib/python3.10/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/dishantpadalia/opt/miniconda3/envs/iitb_2/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/dishantpadalia/opt/miniconda3/envs/iitb_2/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/dishantpadalia/opt/miniconda3/envs/iitb_2/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/dishantpadalia/opt/miniconda3/envs/iitb_2/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'DetectionDataset.__init__.<locals>.<lambda>'
```

### Environment

```
DocTR version: 0.6.0a0
TensorFlow version: N/A
PyTorch version: 1.13.0.dev20220822 (torchvision 0.14.0.dev20220822)
OpenCV version: 4.6.0
OS: Mac OSX 12.5.1
Python version: 3.10.4
Is CUDA available (TensorFlow): N/A
Is CUDA available (PyTorch): No
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
```

### Deep Learning backend

```
>>> from doctr.file_utils import is_tf_available, is_torch_available
>>> print(f"is_tf_available: {is_tf_available()}")
is_tf_available: False
>>> print(f"is_torch_available: {is_torch_available()}")
is_torch_available: True

```

**Comment by felixdittrich92** [comment]
Hi @dishant26 looks like a problem with fastprogress... Would it be possible to test with python 3.8 (Unfortunately i cannot much help on MacOS)

**Comment by dishant26** [comment]
Hey. I tested with python 3.8. Still the same error.

**Comment by dishant26** [comment]
Hey. I solved the issue. It is some problem with lambda functions. 
If anyone encounters the same issue.  Just set ```num_workers=0```  in train_loader.

**Comment by felixdittrich92** [comment]
Hi @dishant26 i think i got it python <3.8 should work seems to be an known issue with multiprocessing and macosx another solution (you posted) or modifying the script to use tqdm instead of fastprogress

**Comment by felixdittrich92** [comment]
Thanks for sharing your solution 👍
