### ISSUE TITLE
Training detection with tags threw me an out of bounds error

### ISSUE THREAD

**Issue by AbrahamIES** [mindee/doctr#1145]
### Discussed in https://github.com/mindee/doctr/discussions/1144

<div type='discussions-op-text'>

<sup>Originally posted by **AbrahamIES** February  9, 2023</sup>
Hi everyone, I was trying to train  db_resnet50 using tags on polygons. I create the train an val files as they suggest 

`{
  "/resources/detection/images/77223.tif": {
    "img_dimensions": [
      1586,
      1857
    ],
    "img_hash": 6597912623780605387,
    "polygons": {
      "fechaInscripcion": [
        [
          [
            1048,
            96
          ],
          [
            1120,
            161
          ]
        ]
       ]`

but when run the training script i get this error

`/home/ml/anaconda3/envs/ocr/lib/python3.10/site-packages/weasyprint/text/fonts.py:63: UserWarning: No fonts configured in FontConfig. Expect ugly output.
  warn('No fonts configured in FontConfig. Expect ugly output.')
Namespace(train_path='/home/ml/proyectos/rnec/ML/resources/detection/', arch='db_resnet50', name=None, epochs=10, batch_size=1, device=None, input_size=1024, lr=0.001, weight_decay=0, workers=0, resume=None, test_only=False, freeze_backbone=False, show_samples=False, wb=False, push_to_hub=False, pretrained=False, rotation=False, eval_straight=False, sched='cosine', amp=False, find_lr=False)
Validation set loaded in 0.04063s (106 samples in 106 batches)
/home/ml/anaconda3/envs/ocr/lib/python3.10/site-packages/torchvision/models/_utils.py:135: UserWarning: Using 'weights' as positional parameter(s) is deprecated since 0.13 and may be removed in the future. Please use keyword parameter(s) instead.
  warnings.warn(
/home/ml/anaconda3/envs/ocr/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
Train set loaded in 0.0585s (564 samples in 564 batches)
Traceback (most recent call last):--------------------------------------------------------------------------------| 0.00% [0/564 00:00<?]
  File "/home/ml/proyectos/rnec/ML/resources/references/detection/train_pytorch.py", line 453, in <module>
    main(args)
  File "/home/ml/proyectos/rnec/ML/resources/references/detection/train_pytorch.py", line 371, in main
    fit_one_epoch(model, train_loader, batch_transforms, optimizer, scheduler, mb, amp=args.amp)
  File "/home/ml/proyectos/rnec/ML/resources/references/detection/train_pytorch.py", line 129, in fit_one_epoch
    train_loss = model(images, targets)["loss"]
  File "/home/ml/anaconda3/envs/ocr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ml/proyectos/rnec/ML/resources/references/detection/doctr/models/detection/differentiable_binarization/pytorch.py", line 222, in forward
    loss = self.compute_loss(logits, thresh_map, target)
  File "/home/ml/proyectos/rnec/ML/resources/references/detection/doctr/models/detection/differentiable_binarization/pytorch.py", line 243, in compute_loss
    targets = self.build_target(target, prob_map.shape, False)  # type: ignore[arg-type]
  File "/home/ml/proyectos/rnec/ML/resources/references/detection/doctr/models/detection/differentiable_binarization/base.py", line 346, in build_target
    cv2.fillPoly(seg_target[idx, class_idx], [shrinked.astype(np.int32)], 1)
IndexError: index 1 is out of bounds for axis 1 with size 1
`
do you know what is the problem?

Thanks</div>

**Comment by AbrahamIES** [comment]
The problem I think, is that I first started with a version of doctr that does not support multiclass detection training. Then I downloaded the doctr repo and I tried to use it as module without installing it and throws me that error. I made a fresh developer installation with the repo and the scripts ran well.
