### ISSUE TITLE
Dependency changed - remove rapidfuzz.string_metric module

### ISSUE THREAD

**Issue by nigelsim** [mindee/doctr#1186]
### Bug description

Following the installation instructions, we end up with `rapidfuzz` 3.0.0, which no longer has `string_metric` module, resulting in:

```
>>> from doctr.models import ocr_predictor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nigel/.virtualenvs/doctr/lib/python3.10/site-packages/doctr/__init__.py", line 1, in <module>
    from . import datasets, io, models, transforms, utils
  File "/home/nigel/.virtualenvs/doctr/lib/python3.10/site-packages/doctr/models/__init__.py", line 4, in <module>
    from .recognition import *
  File "/home/nigel/.virtualenvs/doctr/lib/python3.10/site-packages/doctr/models/recognition/__init__.py", line 5, in <module>
    from .zoo import *
  File "/home/nigel/.virtualenvs/doctr/lib/python3.10/site-packages/doctr/models/recognition/zoo.py", line 12, in <module>
    from .predictor import RecognitionPredictor
  File "/home/nigel/.virtualenvs/doctr/lib/python3.10/site-packages/doctr/models/recognition/predictor/__init__.py", line 6, in <module>
    from .pytorch import *  # type: ignore[misc]
  File "/home/nigel/.virtualenvs/doctr/lib/python3.10/site-packages/doctr/models/recognition/predictor/pytorch.py", line 14, in <module>
    from ._utils import remap_preds, split_crops
  File "/home/nigel/.virtualenvs/doctr/lib/python3.10/site-packages/doctr/models/recognition/predictor/_utils.py", line 10, in <module>
    from ..utils import merge_multi_strings
  File "/home/nigel/.virtualenvs/doctr/lib/python3.10/site-packages/doctr/models/recognition/utils.py", line 8, in <module>
    from rapidfuzz.string_metric import levenshtein
ModuleNotFoundError: No module named 'rapidfuzz.string_metric'

```

### Code snippet to reproduce the bug

```shell
mkvirtualenv doctr
pip install python-doctr
pip install "python-doctr[torch]"
python -c "from doctr.models import ocr_predictor"
```

### Error traceback

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/nigel/.virtualenvs/doctr/lib/python3.10/site-packages/doctr/__init__.py", line 1, in <module>
    from . import datasets, io, models, transforms, utils
  File "/home/nigel/.virtualenvs/doctr/lib/python3.10/site-packages/doctr/models/__init__.py", line 4, in <module>
    from .recognition import *
  File "/home/nigel/.virtualenvs/doctr/lib/python3.10/site-packages/doctr/models/recognition/__init__.py", line 5, in <module>
    from .zoo import *
  File "/home/nigel/.virtualenvs/doctr/lib/python3.10/site-packages/doctr/models/recognition/zoo.py", line 12, in <module>
    from .predictor import RecognitionPredictor
  File "/home/nigel/.virtualenvs/doctr/lib/python3.10/site-packages/doctr/models/recognition/predictor/__init__.py", line 6, in <module>
    from .pytorch import *  # type: ignore[misc]
  File "/home/nigel/.virtualenvs/doctr/lib/python3.10/site-packages/doctr/models/recognition/predictor/pytorch.py", line 14, in <module>
    from ._utils import remap_preds, split_crops
  File "/home/nigel/.virtualenvs/doctr/lib/python3.10/site-packages/doctr/models/recognition/predictor/_utils.py", line 10, in <module>
    from ..utils import merge_multi_strings
  File "/home/nigel/.virtualenvs/doctr/lib/python3.10/site-packages/doctr/models/recognition/utils.py", line 8, in <module>
    from rapidfuzz.string_metric import levenshtein
ModuleNotFoundError: No module named 'rapidfuzz.string_metric'
```

### Environment

DocTR version: N/A
TensorFlow version: N/A
PyTorch version: 2.0.0+cu117 (torchvision 0.15.1+cu117)
OpenCV version: 4.7.0
OS: Ubuntu 22.04.2 LTS
Python version: 3.10.6
Is CUDA available (TensorFlow): N/A
Is CUDA available (PyTorch): No
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

### Deep Learning backend

Can't import due to above error.

**Comment by nigelsim** [comment]
Workaround is to run `pip install rapidfuzz==2.15.1`

**Comment by felixT2K** [comment]
Fixed in #1177 i think we can do a patch release soon :)

**Comment by HamzaGbada** [comment]
Install `doctr` library in developper mode:

```
git clone https://github.com/mindee/doctr.git
pip install -e doctr/.[torch]
```

**Comment by JSv4** [comment]
> Workaround is to run `pip install rapidfuzz==2.15.1`

Just ran into this problem installing the library. This works. Thx

**Comment by np-n** [comment]
For tensorflow `pip install "python-doctr[tf]"` followed by `pip install rapidfuzz==2.15.1`  works for me, and I hope it will also work for you.

**Comment by khalidMindee** [comment]
Fyi, the fix has been integrated with the PR above .
