### ISSUE TITLE
Can't pass the model from HuggingFace Hub to predictor

### ISSUE THREAD

**Issue by lanesket** [mindee/doctr#1214]
### Bug description

1. Problem here, that I can't pass the model from hub to, as the requirement is a specific type but not ResNet.
2. Also, do I understand correctly that I can't have PyTorch and Tensorflow installed at the same time, because judging by the code in this case I won't be able to use PyTorch models?

### Code snippet to reproduce the bug

```python
det_model = from_hub('Felix92/doctr-dummy-torch-resnet50')
print(type(det_model)) # torchvision.models.resnet.ResNet
predictor = ocr_predictor(det_arch=det_model) # ... error here
```

### Error traceback

```
ValueError                                Traceback (most recent call last)
Cell In[11], line 1
----> 1 ocr_predictor(det_arch=det_model)

File [/app/experiments/doctr/doctr/models/zoo.py:103](https://vscode-remote+attached-002dcontainer-002b7b22636f6e7461696e65724e616d65223a222f6f63725f617070222c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d7d.vscode-resource.vscode-cdn.net/app/experiments/doctr/doctr/models/zoo.py:103), in ocr_predictor(det_arch, reco_arch, pretrained, pretrained_backbone, assume_straight_pages, preserve_aspect_ratio, symmetric_pad, export_as_straight_boxes, detect_orientation, detect_language, **kwargs)
     58 def ocr_predictor(
     59     det_arch: Any = "db_resnet50",
     60     reco_arch: Any = "crnn_vgg16_bn",
   (...)
     69     **kwargs: Any,
     70 ) -> OCRPredictor:
     71     """End-to-end OCR architecture using one model for localization, and another for text recognition.
     72 
     73     >>> import numpy as np
   (...)
    100         OCR predictor
    101     """
--> 103     return _predictor(
    104         det_arch,
    105         reco_arch,
    106         pretrained,
    107         pretrained_backbone=pretrained_backbone,
    108         assume_straight_pages=assume_straight_pages,
    109         preserve_aspect_ratio=preserve_aspect_ratio,
...
---> 55         raise ValueError(f"unknown architecture: {type(arch)}")
     57     _model = arch
     58     _model.assume_straight_pages = assume_straight_pages

ValueError: unknown architecture:
```

### Environment

Collecting environment information...

Traceback (most recent call last):
  File "[/app/experiments/collect_env.py](https://vscode-remote+attached-002dcontainer-002b7b22636f6e7461696e65724e616d65223a222f6f63725f617070222c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d7d.vscode-resource.vscode-cdn.net/app/experiments/collect_env.py)", line 356, in <module>
    main()
  File "[/app/experiments/collect_env.py](https://vscode-remote+attached-002dcontainer-002b7b22636f6e7461696e65724e616d65223a222f6f63725f617070222c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d7d.vscode-resource.vscode-cdn.net/app/experiments/collect_env.py)", line 351, in main
    output = get_pretty_env_info()
  File "[/app/experiments/collect_env.py](https://vscode-remote+attached-002dcontainer-002b7b22636f6e7461696e65724e616d65223a222f6f63725f617070222c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d7d.vscode-resource.vscode-cdn.net/app/experiments/collect_env.py)", line 346, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "[/app/experiments/collect_env.py](https://vscode-remote+attached-002dcontainer-002b7b22636f6e7461696e65724e616d65223a222f6f63725f617070222c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d7d.vscode-resource.vscode-cdn.net/app/experiments/collect_env.py)", line 242, in get_env_info
    doctr_str = doctr.__version__ if DOCTR_AVAILABLE else "N[/A](https://vscode-remote+attached-002dcontainer-002b7b22636f6e7461696e65724e616d65223a222f6f63725f617070222c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d7d.vscode-resource.vscode-cdn.net/A)"
AttributeError: module 'doctr' has no attribute '__version__'

### Deep Learning backend

False
True

**Comment by felixdittrich92** [comment]
Hi @lanesket 👋 ,
The resnet50 model is only one of our backbones so not a bug this exception is expected.
To see the full list of available detection architectures check out https://github.com/mindee/doctr/blob/main/doctr/models/detection/zoo.py or the documentation :)

PS: the dummy models which i have pushed to hf are only for internal testing :)

I will update the models on hf soon after wach model has a pretrained checkpoint 👍
