### ISSUE TITLE
cant download CORD dataset

### ISSUE THREAD

**Issue by nikokks** [mindee/doctr#1301]
### Bug description

Hi I can't download CORD dataset

### Code snippet to reproduce the bug

```
    >>> from doctr.datasets import CORD
    >>> train_set = CORD(train=True, download=True)
```

### Error traceback

```
Downloading https://doctr-static.mindee.com/models?id=v0.1.1/cord_train.zip&src=0 to /home/nikkokks/.cache/doctr/datasets/cord_train.zip
 13%|██████████████████▍                                                                                                                              | 207643648/1633132413 [00:07<00:51, 27471376.01it/s]
Failed download. Trying https -> http instead. Downloading http://doctr-static.mindee.com/models?id=v0.1.1/cord_train.zip&src=0 to /home/nikkokks/.cache/doctr/datasets/cord_train.zip
Traceback (most recent call last):
  File "/home/nikkokks/Desktop/github/doctr_FAST/doctr/utils/data.py", line 36, in _urlretrieve
    fh.write(chunk)
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikkokks/Desktop/github/doctr_FAST/doctr/utils/data.py", line 109, in download_from_url
    _urlretrieve(url, file_path)
  File "/home/nikkokks/Desktop/github/doctr_FAST/doctr/utils/data.py", line 36, in _urlretrieve
    fh.write(chunk)
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nikkokks/Desktop/github/doctr_FAST/doctr/datasets/cord.py", line 58, in __init__
    super().__init__(
  File "/home/nikkokks/Desktop/github/doctr_FAST/doctr/datasets/datasets/base.py", line 122, in __init__
    archive_path = download_from_url(url, file_name, file_hash, cache_dir=cache_dir, cache_subdir=cache_subdir)
  File "/home/nikkokks/Desktop/github/doctr_FAST/doctr/utils/data.py", line 114, in download_from_url
    _urlretrieve(url, file_path)
  File "/home/nikkokks/Desktop/github/doctr_FAST/doctr/utils/data.py", line 30, in _urlretrieve
    with urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": USER_AGENT})) as response:
  File "/home/nikkokks/anaconda3/envs/doctr3/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/nikkokks/anaconda3/envs/doctr3/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/nikkokks/anaconda3/envs/doctr3/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/nikkokks/anaconda3/envs/doctr3/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/nikkokks/anaconda3/envs/doctr3/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/nikkokks/anaconda3/envs/doctr3/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 308: Permanent Redirect
```

### Environment

Collecting environment information...

DocTR version: 0.7.0a0
TensorFlow version: 2.13.0
PyTorch version: 2.0.1+cu117 (torchvision 0.15.2+cu117)
OpenCV version: 4.4.0
OS: Ubuntu 20.04.6 LTS
Python version: 3.8.17
Is CUDA available (TensorFlow): Yes
Is CUDA available (PyTorch): Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060 Laptop GPU
Nvidia driver version: 535.86.05
cuDNN version: Could not collect

### Deep Learning backend

```
>>> from doctr.file_utils import is_tf_available, is_torch_available
2023-09-02 15:24:26.145997: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-02 15:24:26.850875: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
>>> 
>>> print(f"is_tf_available: {is_tf_available()}")
is_tf_available: True
>>> print(f"is_torch_available: {is_torch_available()}")
is_torch_available: True
```

**Comment by felixdittrich92** [comment]
Hi :)

`OSError: [Errno 28] No space left on device`
