### ISSUE TITLE
Python-doctr from_url

### ISSUE THREAD

**Issue by yoobi** [mindee/doctr#1326]
### Bug description

Hello,

When trying to use `DocumentFile.from_url(url)` with different url all I get are error, in the snippet you'll find 2 different url which I tried and got the exact same error.

### Code snippet to reproduce the bug

```python
from doctr.models import ocr_predictor

model = ocr_predictor(det_arch='db_resnet50', reco_arch='crnn_vgg16_bn', pretrained=True)

doc = DocumentFile.from_url("https://www.francetvinfo.fr/pictures/uGwaNE-aJq7zHLhZJdzdCd9nyjE/1200x900/2021/03/16/phpCDwGn0.jpg")
# doc = DocumentFile.from_url("https://img.lemde.fr/2021/08/02/0/0/549/322/800/0/75/0/d7b0b0a_29032620-capture.PNG")
output = model(doc)
print(output.export())
```

### Error traceback

```
Traceback (most recent call last):
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/starlette/routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/api/v1/router/ocr.py", line 55, in test
    doc = DocumentFile.from_url("https://www.francetvinfo.fr/pictures/uGwaNE-aJq7zHLhZJdzdCd9nyjE/1200x900/2021/03/16/phpCDwGn0.jpg")
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/doctr/io/reader.py", line 52, in from_url
    pdf_stream = read_html(url)
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/doctr/io/html.py", line 26, in read_html
    return HTML(url, **kwargs).write_pdf()
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/weasyprint/__init__.py", line 252, in write_pdf
    self.render(font_config, counter_style, **options)
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/weasyprint/__init__.py", line 209, in render
    return Document._render(self, font_config, counter_style, options)
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/weasyprint/document.py", line 260, in _render
    context = cls._build_layout_context(
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/weasyprint/document.py", line 239, in _build_layout_context
    style_for = get_all_computed_styles(
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/weasyprint/css/__init__.py", line 1120, in get_all_computed_styles
    for sheet in find_stylesheets(
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/weasyprint/css/__init__.py", line 257, in find_stylesheets
    for wrapper in wrapper_element.query_all('style', 'link'):
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/cssselect2/tree.py", line 298, in <genexpr>
    if any(test(element) for test in tests))
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/cssselect2/tree.py", line 298, in <genexpr>
    if any(test(element) for test in tests))
  File "<string>", line 1, in <lambda>
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/cssselect2/tree.py", line 333, in local_name
    namespace_url, local_name = _split_etree_tag(self.etree_element.tag)
  File "/Users/yoobi/Documents/Gitlab/doctr/doctr-api/venv/lib/python3.9/site-packages/cssselect2/tree.py", line 406, in _split_etree_tag
    assert tag[0] == '{'
AssertionError
```

### Environment

DocTR version: v0.7.0
TensorFlow version: 2.13.0
PyTorch version: N/A (torchvision N/A)
OpenCV version: 4.8.0
OS: Mac OSX 13.5.2
Python version: 3.9.6
Is CUDA available (TensorFlow): Yes
Is CUDA available (PyTorch): N/A
CUDA runtime version: Could not collect
GPU models and configuration: /physical_device:GPU:0
Nvidia driver version: Could not collect
cuDNN version: Could not collect

### Deep Learning backend

is_tf_available: True
is_torch_available: False

**Comment by felixT2K** [comment]
Hi @yoobi 👋🏼,

Excuse the confusion but `from_url` is build to work for websites like www.google.com.
But you can use `from_images`

```
import requests

from doctr.models import ocr_predictor
from doctr.io import DocumentFile

url = "https://www.francetvinfo.fr/pictures/uGwaNE-aJq7zHLhZJdzdCd9nyjE/1200x900/2021/03/16/phpCDwGn0.jpg"

model = ocr_predictor(det_arch='db_resnet50', reco_arch='crnn_mobilenet_v3_large', pretrained=True)

doc = DocumentFile.from_images([requests.get(url).content])
# doc = DocumentFile.from_url("https://img.lemde.fr/2021/08/02/0/0/549/322/800/0/75/0/d7b0b0a_29032620-capture.PNG")
output = model(doc)
print(output.export())
output.show(doc)
```
Let me know if that solved your issue 👍🏼

**Comment by yoobi** [comment]
Hello @felixT2K,

Thank you for your answer, just to be clear, the `from_url` is meant to "take a screenshot" of the webpage and extract data via the model ?

I'll test your snippet soon and will be back to you :)

**Comment by felixT2K** [comment]
Internally it's handled as follow:

- extract html from the webpage
- create a pdf from it (with weasyprint)
- call the `from_pdf` functionality internally to extract each page as image 
- forward into the pipeline

**Comment by yoobi** [comment]
Yes I plan on moving to PyTorch, I'll wait until the model are available on the library.

Your snippet worked for the image ! Thanks again.

The issue is resolved on my end, you can close the issue if you want.

**Comment by felixdittrich92** [comment]
Perfect 🤗
