### ISSUE TITLE
Value Error in Recognition Training

### ISSUE THREAD

**Issue by ArsalanYounus007** [mindee/doctr#1429]
Hello,

I hope you are having a good day. I was working on a task to create a recognizer for Handwriting images.

I am training Visual Transformer Base for my training and using IAM HW dataset (for experimentation) for now.
I am getting the following error in the training epoch.

Any help to resolve the issue is greatly appreciated.

```
Train set loaded in 3.229s (115320 samples in 28830 batches)
Training loss: 2.71964:  21%|████████████████▍                                                             | 6095/28830 [28:04<1:44:44,  3.62it/s]
Traceback (most recent call last):███████████▍                                                             | 6095/28830 [28:04<1:51:47,  3.39it/s]
  File "references/recognition/train_tensorflow.py", line 448, in <module>
    main(args)
  File "references/recognition/train_tensorflow.py", line 346, in main
    fit_one_epoch(model, train_loader, batch_transforms, optimizer, args.amp)
  File "references/recognition/train_tensorflow.py", line 91, in fit_one_epoch
    for images, targets in pbar:
  File "C:\Users\Arsalan\anaconda3\envs\doctr_recognition_training\lib\site-packages\tqdm\std.py", line 1182, in __iter__
    for obj in iterable:
  File "F:\GitHub\doctr\doctr\datasets\loader.py", line 95, in __next__
    samples = list(multithread_exec(self.dataset.__getitem__, indices, threads=self.num_workers))
  File "F:\GitHub\doctr\doctr\utils\multithreading.py", line 49, in multithread_exec
    results = map(lambda x: x, tp.map(func, seq))  # noqa: C417
  File "C:\Users\Arsalan\anaconda3\envs\doctr_recognition_training\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Users\Arsalan\anaconda3\envs\doctr_recognition_training\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Users\Arsalan\anaconda3\envs\doctr_recognition_training\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Arsalan\anaconda3\envs\doctr_recognition_training\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "F:\GitHub\doctr\doctr\datasets\datasets\base.py", line 56, in __getitem__
    img = self.img_transforms(img)
  File "F:\GitHub\doctr\doctr\transforms\modules\tensorflow.py", line 56, in __call__
    x = t(x)
  File "F:\GitHub\doctr\doctr\transforms\modules\base.py", line 216, in __call__
    return self.transform(img) if target is None else self.transform(img, target)  # type: ignore[call-arg]
  File "F:\GitHub\doctr\doctr\transforms\modules\tensorflow.py", line 514, in __call__
    return tf.clip_by_value(random_shadow(x, self.opacity_range), 0, 1)
  File "F:\GitHub\doctr\doctr\transforms\functional\tensorflow.py", line 251, in random_shadow
    shadow_mask = create_shadow_mask(img.shape[:2], **kwargs)
  File "F:\GitHub\doctr\doctr\transforms\functional\base.py", line 191, in create_shadow_mask
    final_contour[1] = expand_line(final_contour[[1, 2]], target_shape)
  File "F:\GitHub\doctr\doctr\transforms\functional\base.py", line 111, in expand_line
    raise ValueError
ValueError
```

**Comment by felixT2K** [comment]
Hi @ArsalanYounus007 👋🏼,

We have faiced this issue already ftm you can uncomment 
https://github.com/mindee/doctr/blob/bcf3cd4649e44800dbd3c838de03a9994c740031/references/recognition/train_tensorflow.py#L232
and 
https://github.com/mindee/doctr/blob/bcf3cd4649e44800dbd3c838de03a9994c740031/references/recognition/train_tensorflow.py#L234

@odulcy-mindee Do you remember if we have added this augmentations after the TF recognition runs ? 😅 
(But yeah anything with the gaussian filter is broken on TF side)

**Comment by ArsalanYounus007** [comment]
Hi @felixT2K,
Thank you for your response, that has resolved the issue that I was getting.

I created a checkpoint and wanted to resume my training. But I am getting the following error. I have tried the folder level in path as well (vitstr_base_20240117-005332/) but got the same error

![Screenshot 2024-01-17 224012](https://github.com/mindee/doctr/assets/34642875/966e2e14-097f-42ce-8a28-ce2b58419bf1)

**Comment by felixdittrich92** [comment]
Hey 😊
See: https://mindee.github.io/doctr/using_doctr/custom_models_training.html#loading-your-custom-trained-model

You missed the navigation to the `/weights` folder :)

**Comment by ArsalanYounus007** [comment]
I see, Actually I got confused because there is no /weights file exactly.
Your solution has solved my problem, Thank you!!
Closing this thread now.

**Comment by odulcy-mindee** [comment]
> @odulcy-mindee Do you remember if we have added this augmentations after the TF recognition runs ? 😅

I think, yes, it was after
