### ISSUE TITLE
ModuleNotFoundError: No module named 'doctr.version'

### ISSUE THREAD

**Issue by tzktz** [mindee/doctr#1525]
### Bug description

Doctr version file is missing..

### Code snippet to reproduce the bug

```
from doctr.io import DocumentFile
from doctr.models import ocr_predictor

model = ocr_predictor(pretrained=True)
# PDF

single_img_doc = DocumentFile.from_images("input.jpg")
# Analyze
result = model(doc)
import matplotlib.pyplot as plt

synthetic_pages = result.synthesize()
plt.imshow(synthetic_pages[0]); plt.axis('off'); plt.show()
```

### Error traceback

```
Traceback (most recent call last):
  File "/home/tamil/doctr/main.py", line 1, in <module>
    from doctr.io import DocumentFile
  File "/home/tamil/doctr/doctr/__init__.py", line 3, in <module>
    from .version import __version__  # noqa: F401
ModuleNotFoundError: No module named 'doctr.version'
```

### Environment

```
Collecting environment information...

DocTR version: N/A
TensorFlow version: 2.15.1
PyTorch version: N/A (torchvision N/A)
OpenCV version: 4.9.0
OS: Ubuntu 22.04.3 LTS
Python version: 3.10.12
Is CUDA available (TensorFlow): No
Is CUDA available (PyTorch): N/A
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4090
Nvidia driver version: 551.86
cuDNN version: Could not collect
```

### Deep Learning backend

```
>>> from doctr.file_utils import is_tf_available, is_torch_available
>>>
>>> print(f"is_tf_available: {is_tf_available()}")
is_tf_available: False
>>> print(f"is_torch_available: {is_torch_available()}")
is_torch_available: True
```

**Comment by felixdittrich92** [comment]
Hi @tzktz :wave:,

Which way have you used to install doctr (conda, pip) / (local installation with pip from cloned repo) ?

**Comment by tzktz** [comment]
> Hi @tzktz 👋,
> 
> Which way have you used to install doctr (conda, pip) / (local installation with pip from cloned repo) ?

i found a solution comment the line from  File "/home/tamil/doctr/doctr/__init__.py", line 3, in <module>
    from .version import __version__  # noqa: F401

**Comment by tzktz** [comment]
@felixdittrich92 i have face result image is not upto quality...fonts are breaks in result image..
```

model = ocr_predictor(pretrained=True)
# PDF
doc = DocumentFile.from_pdf("bankstatement.pdf")
# Analyze
result = model(doc)
import matplotlib.pyplot as plt
plt.imshow(result.synthesize()[0]); plt.axis('off'); plt.show()
```
see the result image..
![Figure_1](https://github.com/mindee/doctr/assets/99823984/afa4a8db-b2af-4097-9087-c43fc388084e)
