### ISSUE TITLE
"The size of tensor a (78) must match the size of tensor b (77) at non-singleton dimension 3" with db_resnet* models

### ISSUE THREAD

**Issue by ForceBru** [mindee/doctr#1650]
# Code

```python
import torch
from doctr.io import DocumentFile
from doctr.models import db_resnet34

doc = DocumentFile.from_pdf("data/raw/1706.03762v7.pdf")
page = torch.tensor(doc[0]).permute([2,0,1]).unsqueeze(0)
print(page.shape)
model = db_resnet34(pretrained=True).eval()

with torch.no_grad():
    out = model(page.float())

print(out.shape)
```

Paper: https://arxiv.org/pdf/1706.03762

# Output

```
> python test_doctr2.py 
torch.Size([1, 3, 1584, 1224])
Traceback (most recent call last):
  File "test_doctr2.py", line 11, in <module>
    out = model(page.float())
          ^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.12/site-packages/doctr/models/detection/differentiable_binarization/pytorch.py", line 193, in forward
    feat_concat = self.fpn(feats)
                  ^^^^^^^^^^^^^^^
  File "venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.12/site-packages/doctr/models/detection/differentiable_binarization/pytorch.py", line 86, in forward
    out.append(self.upsample(out[-1]) + t)
               ~~~~~~~~~~~~~~~~~~~~~~~^~~
RuntimeError: The size of tensor a (78) must match the size of tensor b (77) at non-singleton dimension 3
-> Cannot close object, library is destroyed. This may cause a memory leak!
> 
```

Complains about this line:

https://github.com/mindee/doctr/blob/1cea7d8f7db2c3cf7365be3c7457b7fe67f82ab9/doctr/models/detection/differentiable_binarization/pytorch.py#L86

The problem isn't specific to this PDF or this `db_resnet` model: same error for `db_resnet50` and all other PDFs I've tried.

# Versions

- Python 3.12.1
- torch 2.2.2
- python-doctr 0.8.1

**Comment by felixdittrich92** [comment]
Hi @ForceBru :wave:,

If you want to use only the docTR detection model as standalone you can do this as follow:

```
from doctr.io import DocumentFile
from doctr.models import detection_predictor

doc = [DocumentFile.from_pdf("/home/felix/Desktop/doctr_test_data/PRIVATE/Jugement-avant-dire-droit-2661713.pdf")[0]]
det_model = detection_predictor(
    "db_resnet50",
    pretrained=True,
    preserve_aspect_ratio=True,
    symmetric_pad=True,
    assume_straight_pages=False
).cuda().half()

result = det_model(doc)
print(result)

"""
All coordinates values are relative (restore by x-values * page_width, y-values * page_height)
assume_straight_pages=True

format: [xmin, ymin, xmax, ymax, objectness_score]

[{'words': array([[0.62979508, 0.93652344, 0.67121904, 0.953125  , 0.26049805],
       [0.67812303, 0.93164062, 0.7167854 , 0.953125  , 0.25732422],
       [0.61874869, 0.828125  , 0.7085006 , 0.83984375, 0.55566406],
       ...,
       [0.58146712, 0.04785156, 0.65741105, 0.05957031, 0.59033203],
       [0.45443364, 0.046875  , 0.57732473, 0.06152344, 0.51611328],
       [0.86038846, 0.01269531, 0.91838201, 0.03222656, 0.43457031]])}]

assume_straight_pages=False

format: [[x1, y1], [x2, y2], [x3, y3], [x4, y4], [0, objectness_score]]

[{'words': array([[[0.63215054, 0.93571925],
        [0.6682138 , 0.94209564],
        [0.66472118, 0.95197618],
        [0.62865792, 0.94559979],
        [0.        , 0.37866785]],

       [[0.70767199, 0.92949224],
        [0.71568069, 0.94082034],
        [0.68364623, 0.95214844],
        [0.67563753, 0.94082034],
        [0.        , 0.35401844]],

       [[0.61736789, 0.82714844],
        [0.7071198 , 0.82714844],
        [0.7071198 , 0.83886719],
        [0.61736789, 0.83886719],
        [0.        , 0.66000097]],

       ...,

       [[0.58008624, 0.04785156],
        [0.65326857, 0.04785156],
        [0.65326857, 0.05761719],
        [0.58008624, 0.05761719],
        [0.        , 0.68389305]],

       [[0.45443364, 0.046875  ],
        [0.57456313, 0.046875  ],
        [0.57456313, 0.05957031],
        [0.45443364, 0.05957031],
        [0.        , 0.61274548]],

       [[0.86038846, 0.01269531],
        [0.91562041, 0.01269531],
        [0.91562041, 0.03027344],
        [0.86038846, 0.03027344],
        [0.        , 0.48666838]]])}]
"""
```

NOTE: I suggest to use the main branch instead of v0.8.1 because there was a bug where the padding wasn't removed from the detection results, so if you use v0.8.1 it would be on your own to remove the padding
