### ISSUE TITLE
ValueError: Layer 'conv2d_9' expected 1 variables, but received 0 variables during loading. Expected: ['conv2d_9/kernel:0']

### ISSUE THREAD

**Issue by MuhammadShifa** [mindee/doctr#1792]
### Bug description

Hello thanks for the awesome package. I am going to process a pdf document with OCR but I am facing this issue. I have installed the doctr, tf and pt from source via the following line.
```
git clone https://github.com/mindee/doctr.git
pip install -e doctr/.
# for TensorFlow
pip install -e doctr/.[tf]
# for PyTorch
pip install -e doctr/.[torch]
```

        

### Code snippet to reproduce the bug

```python
from doctr.io import DocumentFile
from doctr.models import kie_predictor

# Model
model = kie_predictor(det_arch='db_resnet50', reco_arch='crnn_vgg16_bn', pretrained=True)
# PDF
doc = DocumentFile.from_pdf("./testing_doctr_ocr.pdf")
# Analyze
result = model(doc)

predictions = result.pages[0].predictions
for class_name in predictions.keys():
    list_predictions = predictions[class_name]
    for prediction in list_predictions:
        print(f"Prediction for {class_name}: {prediction}")```


### Error traceback

```
Traceback (most recent call last):
  File "E:\OCR\ml_mo\doctr_mo\testing_doct.py", line 5, in <module>
    model = kie_predictor(det_arch='db_resnet50', reco_arch='crnn_vgg16_bn', pretrained=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\OCR\ml_mo\doctr\doctr\models\zoo.py", line 228, in kie_predictor
    return _kie_predictor(
           ^^^^^^^^^^^^^^^
  File "E:\OCR\ml_mo\doctr\doctr\models\zoo.py", line 146, in _kie_predictor
    det_predictor = detection_predictor(
                    ^^^^^^^^^^^^^^^^^^^^
  File "E:\OCR\ml_mo\doctr\doctr\models\detection\zoo.py", line 110, in detection_predictor
    return _predictor(
           ^^^^^^^^^^^
  File "E:\OCR\ml_mo\doctr\doctr\models\detection\zoo.py", line 50, in _predictor
    _model = detection.__dict__[arch](
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\OCR\ml_mo\doctr\doctr\models\detection\differentiable_binarization\tensorflow.py", line 390, in db_resnet50
    return _db_resnet(
           ^^^^^^^^^^^
  File "E:\OCR\ml_mo\doctr\doctr\models\detection\differentiable_binarization\tensorflow.py", line 318, in _db_resnet
    load_pretrained_params(
  File "E:\OCR\ml_mo\doctr\doctr\models\utils\tensorflow.py", line 73, in load_pretrained_params
    model.load_weights(archive_path, skip_mismatch=skip_mismatch)
  File "C:\Users\admin\anaconda3\envs\doctr_ocr\Lib\site-packages\tf_keras\src\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\admin\anaconda3\envs\doctr_ocr\Lib\site-packages\tf_keras\src\engine\base_layer.py", line 3518, in load_own_variables
    raise ValueError(
ValueError: Layer 'conv2d_9' expected 1 variables, but received 0 variables during loading. Expected: ['conv2d_9/kernel:0']
```

### Environment

WARNING:tensorflow:From C:\Users\admin\anaconda3\envs\doctr_ocr\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

WARNING:tensorflow:From C:\Users\admin\anaconda3\envs\doctr_ocr\Lib\site-packages\tf2onnx\tf_loader.py:68: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

WARNING:tensorflow:From C:\Users\admin\anaconda3\envs\doctr_ocr\Lib\site-packages\tf2onnx\tf_loader.py:72: The name tf.train.import_meta_graph is deprecated. Please use tf.compat.v1.train.import_meta_graph instead.

WARNING:tensorflow:From C:\Users\admin\anaconda3\envs\doctr_ocr\Lib\site-packages\tf_keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

Collecting environment information...

DocTR version: 0.10.1a0
TensorFlow version: 2.18.0
PyTorch version: 2.5.1+cpu (torchvision 0.20.1+cpu)
OpenCV version: 4.10.0
OS: Microsoft Windows 10 Pro
Python version: 3.11.10
Is CUDA available (TensorFlow): No
Is CUDA available (PyTorch): No
CUDA runtime version: 11.8.89
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
(doctr_ocr) PS E:\OCR\ml_mo\doctr\scripts>


### Deep Learning backend

is_tf_available: True
is_torch_available: True

**Comment by felixdittrich92** [comment]
Hi @MuhammadShifa :wave:,

Thanks for reporting this seems to be an issue with TensorFlow on Windows machines -> https://github.com/mindee/doctr/discussions/1776

CC @odulcy-mindee Do we have a windows machine where we can try to reproduce the bug ? :sweat_smile:

**Comment by MuhammadShifa** [comment]
Hi @felixdittrich92 , @odulcy-mindee 
Yes exactly, I am using the Window Machine.

**Comment by felixdittrich92** [comment]
Quickly tested also with py3.11 in a docker container without issues. 
So it's definitely related to Windows

**Comment by JulianAndhika** [comment]
Currently have the same problem whenever i try to run the ocr_predictor. Any current alternative fix?

**Comment by felixdittrich92** [comment]
> Currently have the same problem whenever i try to run the ocr_predictor. Any current alternative fix?

Hi @JulianAndhika 👋🏼 ,

I expect you use also windows ? 
Doesn't looks like there is an quick fix unfortunately.

What you could do is switching to PyTorch as backend 


btw. which docTR version do you use ?

**Comment by JulianAndhika** [comment]
Hi @felixdittrich92 

Yeah im using windows. I'm currently trying to use OnnxTR as an alternative. I'm currently fine tuning the model using train_tensorflow.py, and was wondering if i could do the same thing on OnnxTR.

Also i was using docTR version 0.10.0

**Comment by felixT2K** [comment]
> Hi @felixdittrich92
> 
> Yeah im using windows. I'm currently trying to use OnnxTR as an alternative. I'm currently fine tuning the model using train_tensorflow.py, and was wondering if i could do the same thing on OnnxTR.
> 
> Also i was using docTR version 0.10.0

OnnxTR is inference only so you can train / fine tune your model with docTR and export it to Onnx as described here:
https://mindee.github.io/doctr/using_doctr/using_model_export.html#export-to-onnx
Afterwards you can load it in OnnxTR :)

**Comment by felixdittrich92** [comment]
Quick update:

I was able to reproduce the issue and as suspected it's a bug in Keras (v2) - happens only on Windows

**Comment by JulianAndhika** [comment]
Hi @felixdittrich92 @felixT2K. That's unfortunate, hopefully the bug could be fixed soon. I've resorted to fine tune the model on colab, since it doesn't seem to be running into the bug when fine tuning. Using pytorch is fine for inference, but when i try fine tuning, it produces an error of

`RuntimeError: Expected tensor to have size at least 36 at dimension 1, but got size 32 for argument #2 'targets' (while checking arguments for ctc_loss_cpu)`

Maybe a bug on pytorch part or something i don't know. Any ideas on what's wrong?

**Comment by felixT2K** [comment]
@MuhammadShifa The pytorch bug is easy to fix your recognition dataset contains samples with more than 32 characters (models max_length) - so keep only samples with <= 30 characters and everything should work as expected

**Comment by Joeweav** [comment]
I thought I was going nuts here.  I started with my own code and kept getting errors and wound up killing the ve, and re-installing very carefully, and this time I set up a test based almost 100% on the reference code:

from doctr.io import DocumentFile
from doctr.models import ocr_predictor, from_hub

#img = DocumentFile.from_images([0.png'])
img = DocumentFile.from_images(["0.png"])
# Load your model from the hub
model = from_hub('Felix92/doctr-dummy-tf-fast-base-v2')

# Pass it to the predictor
# If your model is a recognition model:
predictor = ocr_predictor(det_arch='db_mobilenet_v3_large',
                          reco_arch=model,
                          pretrained=True)

# If your model is a detection model:
predictor = ocr_predictor(det_arch=model,
                          reco_arch='crnn_mobilenet_v3_small',
                          pretrained=True)

# Get your predictions
res = predictor(img)

This is almost exactly right off we web page.  And even with the reference code, and the model that was in it I still get the same error:

ValueError: Layer 'conv2d' expected 1 variables, but received 0 variables during loading. Expected: ['conv2d/kernel:0']

I fully appreciate that is a labor of love for you so to speak, and things take a while to get fixed, but that being said, it would only take a few minutes up update the web page and mention that at least the TF version is not working for Windows right now.  It would have saved me a whole lot of time and head scratching!
