### ISSUE TITLE
OCR failure on certain PDF pages

### ISSUE THREAD

**Issue by vikasr111** [mindee/doctr#1808]
### Bug description

I am trying to perform OCR using DocTR on a PDF document. I have noticed that the OCR for the whole document is failing because of one page in the document. When I ran that individual one-page pdf, I got the full error log. Here's the PDF:
[po-r.pdf](https://github.com/user-attachments/files/17991370/po-r.pdf)

Here's the error log:
```
Traceback (most recent call last):
  File "/app/main.py", line 25, in <module>
    main(args.filename)
  File "/app/main.py", line 12, in main
    doctr_onnx(filename)
  File "/app/doctr_onnx.py", line 394, in doctr_onnx
    result = predictor(docs)
  File "/usr/local/lib/python3.10/site-packages/onnxtr/models/predictor/predictor.py", line 132, in __call__
    word_preds = self.reco_predictor([crop for page_crops in crops for crop in page_crops], **kwargs)
  File "/usr/local/lib/python3.10/site-packages/onnxtr/models/recognition/predictor/base.py", line 67, in __call__
    processed_batches = self.pre_processor(crops)  # type: ignore[arg-type]
  File "/usr/local/lib/python3.10/site-packages/onnxtr/models/preprocessor/base.py", line 105, in __call__
    samples = list(multithread_exec(self.sample_transforms, x))
  File "/usr/local/lib/python3.10/site-packages/onnxtr/utils/multithreading.py", line 47, in multithread_exec
    results = map(lambda x: x, tp.map(func, seq))  # noqa: C417
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.10/site-packages/onnxtr/models/preprocessor/base.py", line 70, in sample_transforms
    x = self.resize(x)
  File "/usr/local/lib/python3.10/site-packages/onnxtr/transforms/base.py", line 58, in __call__
    img_resized = Image.fromarray(img).resize(tmp_size, resample=self.interpolation)
  File "/usr/local/lib/python3.10/site-packages/PIL/Image.py", line 2200, in resize
    return self._new(self.im.resize(size, resample, box))
ValueError: height and width must be > 0
```

I printed the docs of DocTR to debug further and here's the result:
```
Number of pages in po-r.pdf: 1
Pages: [array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]], dtype=uint8)]
```

### Code snippet to reproduce the bug

```
from doctr.models import ocr_predictor
from doctr.io import DocumentFile

# load image
pdf_path = "./data/invoice/po-r.pdf"

# extracting text from input image using docTR
docs = DocumentFile.from_pdf(pdf_path)

# load model
predictor = ocr_predictor(
    det_arch="db_mobilenet_v3_large",
    reco_arch="parseq",
    pretrained=True,
    preserve_aspect_ratio=False,
    symmetric_pad=False,
    )

predictor.det_predictor.model.postprocessor.bin_thresh = 0.35
predictor.det_predictor.model.postprocessor.box_thresh = 0.3


result = predictor(docs)

# display ocr boxes
result.show(docs)
```

### Error traceback

Here's the error log:
```
Traceback (most recent call last):
  File "/app/main.py", line 25, in <module>
    main(args.filename)
  File "/app/main.py", line 12, in main
    doctr_onnx(filename)
  File "/app/doctr_onnx.py", line 394, in doctr_onnx
    result = predictor(docs)
  File "/usr/local/lib/python3.10/site-packages/onnxtr/models/predictor/predictor.py", line 132, in __call__
    word_preds = self.reco_predictor([crop for page_crops in crops for crop in page_crops], **kwargs)
  File "/usr/local/lib/python3.10/site-packages/onnxtr/models/recognition/predictor/base.py", line 67, in __call__
    processed_batches = self.pre_processor(crops)  # type: ignore[arg-type]
  File "/usr/local/lib/python3.10/site-packages/onnxtr/models/preprocessor/base.py", line 105, in __call__
    samples = list(multithread_exec(self.sample_transforms, x))
  File "/usr/local/lib/python3.10/site-packages/onnxtr/utils/multithreading.py", line 47, in multithread_exec
    results = map(lambda x: x, tp.map(func, seq))  # noqa: C417
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.10/site-packages/onnxtr/models/preprocessor/base.py", line 70, in sample_transforms
    x = self.resize(x)
  File "/usr/local/lib/python3.10/site-packages/onnxtr/transforms/base.py", line 58, in __call__
    img_resized = Image.fromarray(img).resize(tmp_size, resample=self.interpolation)
  File "/usr/local/lib/python3.10/site-packages/PIL/Image.py", line 2200, in resize
    return self._new(self.im.resize(size, resample, box))
ValueError: height and width must be > 0
```

### Environment

Python - 3.11.7

### Deep Learning backend

Torch

**Comment by felixdittrich92** [comment]
Thanks for reporting :+1: 

Would it be possible to share such an pdf that we can reproduce the issue ?
And i see it's OnnxTR related ^^

```
/usr/local/lib/python3.10/site-packages/onnxtr/transforms/base.py
```

**Comment by vikasr111** [comment]
Here's the pdf link: https://github.com/user-attachments/files/17991370/po-r.pdf

I ran it through both DocTR and OnnxTR and ran into same problem.

**Comment by felixdittrich92** [comment]
`result.show(docs)` is outdated btw it's only `result.show()` since v0.9 if i remember correctly

**Comment by felixdittrich92** [comment]
Maybe an issue with pypdfium2 ?
What do you use as base image in your dockerfile ?
