### ISSUE TITLE
python 3.13 compatibility issues (windows)

### ISSUE THREAD

**Issue by diegonc** [mindee/doctr#1814]
### Bug description

On Windows old versions of Python have no installer available. With the current release, 3.13.1, doctr fails to install due to matplotlib required dependency version being too old.

### Code snippet to reproduce the bug

I have problems running the pip install comand. Log pasted in the error traceback field below.

### Error traceback

```
PS D:\work\bank\alpha2000> D:\diego\PROGRAMACION\Compiladores\Python3.13.1\python.exe -m pip install python-doctr python-doctr[torch]
Collecting python-doctr
  Using cached python_doctr-0.10.0-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: numpy<3.0.0,>=1.16.0 in d:\diego\programacion\compiladores\python3.13.1\lib\site-packages (from python-doctr) (2.1.3)
Collecting scipy<2.0.0,>=1.4.0 (from python-doctr)
  Using cached scipy-1.14.1-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting h5py<4.0.0,>=3.1.0 (from python-doctr)
  Using cached h5py-3.12.1-cp313-cp313-win_amd64.whl.metadata (2.5 kB)
Collecting opencv-python<5.0.0,>=4.5.0 (from python-doctr)
  Using cached opencv_python-4.10.0.84-cp37-abi3-win_amd64.whl.metadata (20 kB)
Collecting pypdfium2<5.0.0,>=4.11.0 (from python-doctr)
  Using cached pypdfium2-4.30.0-py3-none-win_amd64.whl.metadata (48 kB)
Collecting pyclipper<2.0.0,>=1.2.0 (from python-doctr)
  Using cached pyclipper-1.3.0.post6-cp313-cp313-win_amd64.whl.metadata (9.2 kB)
Collecting shapely<3.0.0,>=1.6.0 (from python-doctr)
  Using cached shapely-2.0.6-cp313-cp313-win_amd64.whl.metadata (7.2 kB)
Collecting langdetect<2.0.0,>=1.0.9 (from python-doctr)
  Using cached langdetect-1.0.9.tar.gz (981 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting rapidfuzz<4.0.0,>=3.0.0 (from python-doctr)
  Using cached rapidfuzz-3.10.1-cp313-cp313-win_amd64.whl.metadata (11 kB)
Collecting huggingface-hub<1.0.0,>=0.20.0 (from python-doctr)
  Using cached huggingface_hub-0.26.3-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: Pillow>=9.2.0 in d:\diego\programacion\compiladores\python3.13.1\lib\site-packages (from python-doctr) (11.0.0)
Collecting defusedxml>=0.7.0 (from python-doctr)
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
Collecting anyascii>=0.3.2 (from python-doctr)
  Using cached anyascii-0.3.2-py3-none-any.whl.metadata (1.5 kB)
Collecting tqdm>=4.30.0 (from python-doctr)
  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
INFO: pip is looking at multiple versions of python-doctr[torch] to determine which version is compatible with other requirements. This could take a while.
Collecting python-doctr[torch]
  Using cached python_doctr-0.9.0-py3-none-any.whl.metadata (33 kB)
Collecting numpy<3.0.0,>=1.16.0 (from python-doctr)
  Using cached numpy-1.26.4.tar.gz (15.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting python-doctr[torch]
  Using cached python_doctr-0.8.1-py3-none-any.whl.metadata (33 kB)
Collecting importlib-metadata (from python-doctr[torch])
  Using cached importlib_metadata-8.5.0-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: matplotlib>=3.1.0 in d:\diego\programacion\compiladores\python3.13.1\lib\site-packages (from python-doctr[torch]) (3.9.3)
Collecting weasyprint>=55.0 (from python-doctr[torch])
  Using cached weasyprint-63.0-py3-none-any.whl.metadata (3.7 kB)
Collecting mplcursors>=0.3 (from python-doctr[torch])
  Using cached mplcursors-0.6-py3-none-any.whl.metadata (3.0 kB)
Collecting unidecode>=1.0.0 (from python-doctr[torch])
  Using cached Unidecode-1.3.8-py3-none-any.whl.metadata (13 kB)
Collecting python-doctr[torch]
  Using cached python_doctr-0.8.0-py3-none-any.whl.metadata (32 kB)
  Using cached python_doctr-0.7.0-py3-none-any.whl.metadata (31 kB)
  Using cached python_doctr-0.6.0-py3-none-any.whl.metadata (29 kB)
  Using cached python_doctr-0.5.1-py3-none-any.whl.metadata (17 kB)
Collecting matplotlib<3.4.3,>=3.1.0 (from python-doctr[torch])
  Using cached matplotlib-3.4.2.tar.gz (37.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [42 lines of output]
      <string>:34: SetuptoolsDeprecationWarning: The test command is disabled and references to it are deprecated.
      !!

              ********************************************************************************
              Please remove any references to `setuptools.command.test` in all supported versions of the affected package.

              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.
              ********************************************************************************

      !!
      Traceback (most recent call last):
        File "D:\diego\PROGRAMACION\Compiladores\Python3.13.1\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "D:\diego\PROGRAMACION\Compiladores\Python3.13.1\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\diego\PROGRAMACION\Compiladores\Python3.13.1\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\diego\AppData\Local\Temp\pip-build-env-lnnrzou1\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\diego\AppData\Local\Temp\pip-build-env-lnnrzou1\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\diego\AppData\Local\Temp\pip-build-env-lnnrzou1\overlay\Lib\site-packages\setuptools\build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\diego\AppData\Local\Temp\pip-build-env-lnnrzou1\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 54, in <module>
        File "C:\Users\diego\AppData\Local\Temp\pip-install-p10stg59\matplotlib_ef20dde5681b46e59e1cc4ca0f3ede3d\versioneer.py", line 1410, in get_version
          return get_versions()["version"]
                 ~~~~~~~~~~~~^^
        File "C:\Users\diego\AppData\Local\Temp\pip-install-p10stg59\matplotlib_ef20dde5681b46e59e1cc4ca0f3ede3d\versioneer.py", line 1344, in get_versions
          cfg = get_config_from_root(root)
        File "C:\Users\diego\AppData\Local\Temp\pip-install-p10stg59\matplotlib_ef20dde5681b46e59e1cc4ca0f3ede3d\versioneer.py", line 401, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### Environment

```
PS D:\work\bank\alpha2000> D:\diego\PROGRAMACION\Compiladores\Python3.13.1\python.exe collect_env.py
Collecting environment information...

DocTR version: N/A
TensorFlow version: N/A
PyTorch version: N/A (torchvision N/A)
OpenCV version: N/A
OS: Microsoft Windows 11 Home
Python version: 3.13.1
Is CUDA available (TensorFlow): N/A
Is CUDA available (PyTorch): N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
```

### Deep Learning backend

I can't run the snippet because the problem is installing the library.

**Comment by diegonc** [comment]
It neither works on linux:

```
nexitel@n9:~/doctr/py3.13.1$ pyenv activate .venv
(.venv) nexitel@n9:~/doctr/py3.13.1$ python -V
Python 3.13.1
(.venv) nexitel@n9:~/doctr/py3.13.1$ pip install python-doctr python-doctr[torch]
Collecting python-doctr
  Downloading python_doctr-0.10.0-py3-none-any.whl.metadata (33 kB)
Collecting numpy<3.0.0,>=1.16.0 (from python-doctr)
  Downloading numpy-2.1.3-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Collecting scipy<2.0.0,>=1.4.0 (from python-doctr)
  Downloading scipy-1.14.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
Collecting h5py<4.0.0,>=3.1.0 (from python-doctr)
  Downloading h5py-3.12.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
Collecting opencv-python<5.0.0,>=4.5.0 (from python-doctr)
  Downloading opencv_python-4.10.0.84-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Collecting pypdfium2<5.0.0,>=4.11.0 (from python-doctr)
  Downloading pypdfium2-4.30.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (48 kB)
Collecting pyclipper<2.0.0,>=1.2.0 (from python-doctr)
  Downloading pyclipper-1.3.0.post6-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.0 kB)
Collecting shapely<3.0.0,>=1.6.0 (from python-doctr)
  Downloading shapely-2.0.6-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.0 kB)
Collecting langdetect<2.0.0,>=1.0.9 (from python-doctr)
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 6.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting rapidfuzz<4.0.0,>=3.0.0 (from python-doctr)
  Downloading rapidfuzz-3.10.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Collecting huggingface-hub<1.0.0,>=0.20.0 (from python-doctr)
  Downloading huggingface_hub-0.26.3-py3-none-any.whl.metadata (13 kB)
Collecting Pillow>=9.2.0 (from python-doctr)
  Downloading pillow-11.0.0-cp313-cp313-manylinux_2_28_x86_64.whl.metadata (9.1 kB)
Collecting defusedxml>=0.7.0 (from python-doctr)
  Downloading defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
Collecting anyascii>=0.3.2 (from python-doctr)
  Downloading anyascii-0.3.2-py3-none-any.whl.metadata (1.5 kB)
Collecting tqdm>=4.30.0 (from python-doctr)
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Collecting torch<3.0.0,>=2.0.0 (from python-doctr[torch])
  Downloading torch-2.5.1-cp313-cp313-manylinux1_x86_64.whl.metadata (28 kB)
INFO: pip is looking at multiple versions of python-doctr[torch] to determine which version is compatible with other requirements. This could take a while.
Collecting python-doctr[torch]
  Downloading python_doctr-0.9.0-py3-none-any.whl.metadata (33 kB)
Collecting numpy<3.0.0,>=1.16.0 (from python-doctr)
  Downloading numpy-1.26.4.tar.gz (15.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.8/15.8 MB 8.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting python-doctr[torch]
  Downloading python_doctr-0.8.1-py3-none-any.whl.metadata (33 kB)
Collecting importlib-metadata (from python-doctr[torch])
  Downloading importlib_metadata-8.5.0-py3-none-any.whl.metadata (4.8 kB)
Collecting matplotlib>=3.1.0 (from python-doctr[torch])
  Downloading matplotlib-3.9.3-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Collecting weasyprint>=55.0 (from python-doctr[torch])
  Downloading weasyprint-63.0-py3-none-any.whl.metadata (3.7 kB)
Collecting mplcursors>=0.3 (from python-doctr[torch])
  Downloading mplcursors-0.6-py3-none-any.whl.metadata (3.0 kB)
Collecting unidecode>=1.0.0 (from python-doctr[torch])
  Downloading Unidecode-1.3.8-py3-none-any.whl.metadata (13 kB)
Collecting python-doctr[torch]
  Downloading python_doctr-0.8.0-py3-none-any.whl.metadata (32 kB)
  Downloading python_doctr-0.7.0-py3-none-any.whl.metadata (31 kB)
  Downloading python_doctr-0.6.0-py3-none-any.whl.metadata (29 kB)
  Downloading python_doctr-0.5.1-py3-none-any.whl.metadata (17 kB)
Collecting matplotlib<3.4.3,>=3.1.0 (from python-doctr[torch])
  Downloading matplotlib-3.4.2.tar.gz (37.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.3/37.3 MB 6.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [42 lines of output]
      <string>:34: SetuptoolsDeprecationWarning: The test command is disabled and references to it are deprecated.
      !!
      
              ********************************************************************************
              Please remove any references to `setuptools.command.test` in all supported versions of the affected package.
      
              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.
              ********************************************************************************
      
      !!
      Traceback (most recent call last):
        File "/home/nexitel/.pyenv/versions/3.13.1/envs/.venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/home/nexitel/.pyenv/versions/3.13.1/envs/.venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/nexitel/.pyenv/versions/3.13.1/envs/.venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-ibrd8nwo/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-ibrd8nwo/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-ibrd8nwo/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-ibrd8nwo/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 54, in <module>
        File "/tmp/pip-install-ctjff1fx/matplotlib_1fcc78c205934310abf33e2fd1da2b88/versioneer.py", line 1410, in get_version
          return get_versions()["version"]
                 ~~~~~~~~~~~~^^
        File "/tmp/pip-install-ctjff1fx/matplotlib_1fcc78c205934310abf33e2fd1da2b88/versioneer.py", line 1344, in get_versions
          cfg = get_config_from_root(root)
        File "/tmp/pip-install-ctjff1fx/matplotlib_1fcc78c205934310abf33e2fd1da2b88/versioneer.py", line 401, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by felixdittrich92** [comment]
Hi @diegonc 👋🏼,

It's not recommended to use the latest python release (instead use 3.10, 3.11 or 3.12) because as you can see some dependencies (for example matplotlib) aren't compatible with the latest python release yet - for wider used packages it mostly takes a few weeks after a new python release.
Unfortunately we can't do anything here because it's related to matplotlib.

We could pin our requirements to the previous released minor python version, but personally i would like to avoid this because most users use a stable python version (currently py3.10 & 3.11) so the upper boundary isn't needed normally ^^

Best,
Felix

**Comment by diegonc** [comment]
```
Collecting matplotlib<3.4.3,>=3.1.0 (from python-doctr[torch])
```

The problem is that newer versions of matplotlib are not allowed. If they were, there would be no issue installing. (pip install matplotlib works for instance)

Anyway, I finally found some python 3.12 installer for Windows (they like to remove the old installers :S )  and it's working ok

**Comment by felixdittrich92** [comment]
Ah got it now 😅👍🏼 I will check this tomorrow but great to hear that it works now :)

**Comment by felixdittrich92** [comment]
It's not pinned by use so any other dependency has pinned it to `<3.4.3` 🤔 

https://github.com/mindee/doctr/blob/48873e005ecf5f57c55789d83d71ade9aef1457e/pyproject.toml#L70

**Comment by diegonc** [comment]
Hmm,  and that pin is for python-doctr[viz] which I didn't use. I guess it will eventually be fixed by itself 😝

**Comment by felixdittrich92** [comment]
So i think we can close this :) 
Otherwise feel free to re-open :+1:
