### ISSUE TITLE
OSError: no library called "cairo" was found

### ISSUE THREAD

**Issue by jonathanMindee** [mindee/doctr#264]
## 🐛 Bug

I installed doctr on macOS Mojave 10.14.6, python version 3.8.

When running the sample code: 

```
from doctr.documents import DocumentFile
from doctr.models import ocr_predictor

model = ocr_predictor(pretrained=True)
# PDF
doc = DocumentFile.from_images(["table.png"])
# Analyze
result = model(doc)
```

I get the error:

```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from doctr.documents import DocumentFile
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/doctr/__init__.py", line 2, in <module>
    from . import documents, models, transforms, utils
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/doctr/documents/__init__.py", line 2, in <module>
    from .reader import *
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/doctr/documents/reader.py", line 10, in <module>
    from weasyprint import HTML
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/weasyprint/__init__.py", line 469, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/weasyprint/css/__init__.py", line 27, in <module>
    from . import computed_values, counters, media_queries
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/weasyprint/css/computed_values.py", line 15, in <module>
    from .. import text
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/weasyprint/text.py", line 11, in <module>
    import cairocffi as cairo
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cairocffi/__init__.py", line 48, in <module>
    cairo = dlopen(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cairocffi/__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': dlopen(libcairo.so.2, 2): image not found
cannot load library 'libcairo.2.dylib': dlopen(libcairo.2.dylib, 2): image not found
cannot load library 'libcairo-2.dll': dlopen(libcairo-2.dll, 2): image not found

```

**Comment by fg-mindee** [comment]
Thanks, I'll add a CI job to install on a MacOS environment (#265) !
For reference, given the traceback, the error is most likely due to https://github.com/Kozea/WeasyPrint/issues/1279 & https://github.com/Kozea/WeasyPrint/issues/79 . I'll confirm that adding the MacOS job, and will probably fix this by installing the prerequisites from https://weasyprint.readthedocs.io/en/stable/install.html#macos

**Comment by fg-mindee** [comment]
I'm editing the installation instructions for MacOS users in the PR I just mentioned, here is how to solve your problem:
```shell
brew install cairo pango gdk-pixbuf libffi
```

SImply put, there is a recent new dependency (weasyprint) whose own deps are included on Ubuntu but not on MacOS or Windows. The PR will solve this :ok_hand:
