### ISSUE TITLE
[models] Cannot load MASTER weights

### ISSUE THREAD

**Issue by charlesmindee** [mindee/doctr#353]
## 🐛 Bug

I can't load MASTER weights in TF with the` load_pretrained_params` function.

## To Reproduce

```
from doctr.models import recognition
from doctr.models.utils import load_pretrained_params
from doctr.datasets import VOCABS

master = recognition.MASTER(vocab=VOCABS['french'], input_shape=(32, 128, 3))

load_pretrained_params(master, url="https://github.com/mindee/doctr/releases/download/v0.3.0/master.zip")

```
yields:

```
Traceback (most recent call last):
  File "/home/laptopmindee/doctr/text.py", line 8, in <module>
    load_pretrained_params(master, url="https://github.com/mindee/doctr/releases/download/v0.3.0/master.zip")
  File "/home/laptopmindee/doctr/doctr/models/utils/tensorflow.py", line 50, in load_pretrained_params
    with ZipFile(archive_path, 'r') as f:
  File "/usr/lib/python3.8/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

## Expected behavior

I expected the weights to be loaded properly 

## Environment

```
DocTR version: 0.3.0a0
TensorFlow version: 2.4.1
PyTorch version: 1.9.0+cu111 (torchvision 0.10.0+cu111)
OpenCV version: 4.5.1
OS: Ubuntu 18.04.5 LTS
Python version: 3.8
Is CUDA available (TensorFlow): Yes
Is CUDA available (PyTorch): Yes
CUDA runtime version: 11.0.194
GPU models and configuration: GPU 0: GeForce RTX 2060
Nvidia driver version: 450.80.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
```

**Comment by charlesmindee** [comment]
The weights are a bit heavy (256MB), maybe this is linked to the issue.

**Comment by charlesmindee** [comment]
Can you reproduce the bug @fg-mindee ?

**Comment by fg-mindee** [comment]
I just tried, on my end, it's loading properly :man_shrugging:

**Comment by charlesmindee** [comment]
Ok, should I close the issue ?

**Comment by fg-mindee** [comment]
I think we need to know where it comes from if you have the issue consistently. Perhaps we have a difference in our environment?

I can see that we have different versions of TF & Ubuntu

Here is mine according to the env collection script:
```shell
DocTR version: 0.3.1a0
TensorFlow version: 2.5.0
PyTorch version: 1.9.0 (torchvision 0.10.0)
OpenCV version: 4.5.1
OS: Ubuntu 20.04.2 LTS
Python version: 3.8
Is CUDA available (TensorFlow): Yes
Is CUDA available (PyTorch): Yes
CUDA runtime version: 11.2.152
GPU models and configuration: GPU 0: GeForce RTX 2070 with Max-Q Design
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.0
```

Perhaps if you try upgrading TF?

**Comment by charlesmindee** [comment]
On this environment it works perfectly fine:

```
DocTR version: 0.3.0a0
TensorFlow version: 2.3.1
PyTorch version: 1.6.0 (torchvision 0.7.0)
OpenCV version: 4.4.0
OS: Ubuntu 18.04.5 LTS
Python version: 3.6
Is CUDA available (TensorFlow): Yes
Is CUDA available (PyTorch): Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 460.80
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
```
I guess it is a hardware issue...

**Comment by charlesmindee** [comment]
Not an issue anymore with this environment update:

```
DocTR version: 0.3.1a0
TensorFlow version: 2.5.0
PyTorch version: 1.9.0+cu111 (torchvision 0.10.0+cu111)
OpenCV version: 4.5.1
OS: Ubuntu 18.04.5 LTS
Python version: 3.8
Is CUDA available (TensorFlow): Yes
Is CUDA available (PyTorch): Yes
CUDA runtime version: 11.4.100
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2060
Nvidia driver version: 470.57.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.2
```
Closing this for now

**Comment by fg-mindee** [comment]
So TF 2.4.1 might be the prime suspect here :thinking:
