### ISSUE TITLE
problem exporting saved_model

### ISSUE THREAD

**Issue by khalidMindee** [mindee/doctr#602]
### Bug description

When loading a recognition model, I am unable to export the corresponding saved_model after one step of training . 

### Code snippet to reproduce the bug

```python
import os
import string

import numpy as np
import tensorflow as tf
from doctr.models import recognition

# train params
initial_lr = 1e-3
nb_steps = 10
batch_size = 16
input_shape = (20, 150, 3)
max_length = 34
output_dir = "output/test"

os.makedirs(output_dir, exist_ok=True)

# traindata sample
train_ims = tf.convert_to_tensor(np.ones((batch_size, *input_shape)), dtype=tf.float32)
train_labels = ["ABCD123456"] * batch_size

# Optimizer
scheduler = tf.keras.optimizers.schedules.ExponentialDecay(
    initial_lr, decay_steps=nb_steps, decay_rate=1 / (25e4), staircase=False  # final lr as a fraction of initial lr
)
optimizer = tf.keras.optimizers.Adam(learning_rate=scheduler, beta_1=0.95, beta_2=0.99, epsilon=1e-6, clipnorm=5)

# model loading
_model = recognition.__dict__["sar_resnet31"](
    pretrained=False,
    input_shape=input_shape,
    vocab=string.ascii_uppercase + string.digits,
    max_length=max_length
)
# model save works
tf.saved_model.save(_model, output_dir)

# one step training
with tf.GradientTape() as tape:
    train_loss = _model(train_ims, train_labels, training=True)["loss"]
grads = tape.gradient(train_loss, _model.trainable_weights)
optimizer.apply_gradients(zip(grads, _model.trainable_weights))

# model save doesn't work
tf.saved_model.save(_model, output_dir)

```

### Error traceback

```
Traceback (most recent call last):
  File "/home/khalid/Bureau/projects/invoice_v3/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-12-e53061103513>", line 45, in <module>
    tf.saved_model.save(_model, output_dir)
  File "/home/khalid/Bureau/projects/invoice_v3/venv/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py", line 1032, in save
    _, exported_graph, object_saver, asset_info = _build_meta_graph(
  File "/home/khalid/Bureau/projects/invoice_v3/venv/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py", line 1198, in _build_meta_graph
    return _build_meta_graph_impl(obj, signatures, options, meta_graph_def)
  File "/home/khalid/Bureau/projects/invoice_v3/venv/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py", line 1132, in _build_meta_graph_impl
    signatures = signature_serialization.find_function_to_export(
  File "/home/khalid/Bureau/projects/invoice_v3/venv/lib/python3.8/site-packages/tensorflow/python/saved_model/signature_serialization.py", line 75, in find_function_to_export
    functions = saveable_view.list_functions(saveable_view.root)
  File "/home/khalid/Bureau/projects/invoice_v3/venv/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py", line 150, in list_functions
    obj_functions = obj._list_functions_for_serialization(  # pylint: disable=protected-access
  File "/home/khalid/Bureau/projects/invoice_v3/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 2610, in _list_functions_for_serialization
    functions = super(
  File "/home/khalid/Bureau/projects/invoice_v3/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 3086, in _list_functions_for_serialization
    return (self._trackable_saved_model_saver
  File "/home/khalid/Bureau/projects/invoice_v3/venv/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/base_serialization.py", line 94, in list_functions_for_serialization
    fns = self.functions_to_serialize(serialization_cache)
  File "/home/khalid/Bureau/projects/invoice_v3/venv/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 78, in functions_to_serialize
    return (self._get_serialized_attributes(
  File "/home/khalid/Bureau/projects/invoice_v3/venv/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 94, in _get_serialized_attributes
    object_dict, function_dict = self._get_serialized_attributes_internal(
  File "/home/khalid/Bureau/projects/invoice_v3/venv/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/model_serialization.py", line 51, in _get_serialized_attributes_internal
    default_signature = save_impl.default_save_signature(self.obj)
  File "/home/khalid/Bureau/projects/invoice_v3/venv/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 205, in default_save_signature
    fn.get_concrete_function()
  File "/home/khalid/Bureau/projects/invoice_v3/venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 1299, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/home/khalid/Bureau/projects/invoice_v3/venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 1205, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/home/khalid/Bureau/projects/invoice_v3/venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 725, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/home/khalid/Bureau/projects/invoice_v3/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/home/khalid/Bureau/projects/invoice_v3/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/khalid/Bureau/projects/invoice_v3/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3196, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/home/khalid/Bureau/projects/invoice_v3/venv/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/khalid/Bureau/projects/invoice_v3/venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/khalid/Bureau/projects/invoice_v3/venv/lib/python3.8/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 135, in _wrapped_model
    outputs = model(inputs, training=False)
  File "/home/khalid/Bureau/projects/invoice_v3/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/khalid/Bureau/projects/invoice_v3/venv/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 620, in wrapper
    return func(*args, **kwargs)
  File "/home/khalid/Bureau/projects/doctr/doctr/doctr/models/recognition/sar/tensorflow.py", line 263, in call
    decoded_features = self.decoder(features, encoded, gt=None if target is None else gt, **kwargs)
  File "/home/khalid/Bureau/projects/invoice_v3/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/khalid/Bureau/projects/invoice_v3/venv/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 620, in wrapper
    return func(*args, **kwargs)
  File "/home/khalid/Bureau/projects/doctr/doctr/doctr/models/recognition/sar/tensorflow.py", line 129, in call
    states = self.lstm_decoder.get_initial_state(
  File "/home/khalid/Bureau/projects/invoice_v3/venv/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 126, in get_initial_state
    initial_states.append(get_initial_state_fn(
  File "/home/khalid/Bureau/projects/invoice_v3/venv/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2506, in get_initial_state
    return list(_generate_zero_filled_state_for_cell(
  File "/home/khalid/Bureau/projects/invoice_v3/venv/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2987, in _generate_zero_filled_state_for_cell
    return _generate_zero_filled_state(batch_size, cell.state_size, dtype)
  File "/home/khalid/Bureau/projects/invoice_v3/venv/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2993, in _generate_zero_filled_state
    raise ValueError(
ValueError: batch_size and dtype cannot be None while constructing initial state: batch_size=None, dtype=<dtype: 'float32'>
```

### Environment

Collecting environment information...

DocTR version: 0.4.1a0
TensorFlow version: 2.4.4
PyTorch version: N/A (torchvision N/A)
OpenCV version: 4.5.4-dev
OS: Ubuntu 18.04.5 LTS
Python version: 3.8.12
Is CUDA available (TensorFlow): No
Is CUDA available (PyTorch): N/A
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2060
Nvidia driver version: 465.19.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.0
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_train.so.8

**Comment by fg-mindee** [comment]
Hi @khalidMindee,

As I suspected, this isn't due to training but only because inputs were passed in the model triggering the lazy initialization of kernels. Here is a snippet to reproduce the error:

```python
import string
import tensorflow as tf

from doctr.models.recognition import sar_resnet31
model = sar_resnet31(input_shape=(20, 150, 3), vocab=string.ascii_uppercase + string.digits, max_length=34)
# This works but throws a warning "Skipping full serialization of Keras layer SAR [...] because it is not built"
tf.saved_model.save(model, "tf_svm")
# One forward
_ = model(tf.random.uniform(shape=[1, 20, 150, 3], maxval=1, dtype=tf.float32))
# This produces the same error as before
tf.saved_model.save(model, "tf_svm")
```

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-19f0bd922815> in <module>
----> 1 tf.saved_model.save(model, "tf_svm")

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py in save(obj, export_dir, signatures, options)
   1191   # pylint: enable=line-too-long
   1192   metrics.IncrementWriteApi(_SAVE_V2_LABEL)
-> 1193   save_and_return_nodes(obj, export_dir, signatures, options)
   1194   metrics.IncrementWrite()
   1195 

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py in save_and_return_nodes(obj, export_dir, signatures, options, experimental_skip_checkpoint)
   1226 
   1227   _, exported_graph, object_saver, asset_info, saved_nodes, node_paths = (
-> 1228       _build_meta_graph(obj, signatures, options, meta_graph_def))
   1229   saved_model.saved_model_schema_version = (
   1230       pywrap_libexport.SAVED_MODEL_SCHEMA_VERSION)

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py in _build_meta_graph(obj, signatures, options, meta_graph_def)
   1397 
   1398   with save_context.save_context(options):
-> 1399     return _build_meta_graph_impl(obj, signatures, options, meta_graph_def)

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py in _build_meta_graph_impl(obj, signatures, options, meta_graph_def)
   1333   checkpoint_graph_view = _AugmentedGraphView(obj)
   1334   if signatures is None:
-> 1335     signatures = signature_serialization.find_function_to_export(
   1336         checkpoint_graph_view)
   1337 

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/saved_model/signature_serialization.py in find_function_to_export(saveable_view)
     97   # If the user did not specify signatures, check the root object for a function
     98   # that can be made into a signature.
---> 99   functions = saveable_view.list_functions(saveable_view.root)
    100   signature = functions.get(DEFAULT_SIGNATURE_ATTR, None)
    101   if signature is not None:

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py in list_functions(self, obj)
    161     obj_functions = self._functions.get(obj, None)
    162     if obj_functions is None:
--> 163       obj_functions = obj._list_functions_for_serialization(  # pylint: disable=protected-access
    164           self._serialization_cache)
    165       self._functions[obj] = obj_functions

~/miniconda3/lib/python3.8/site-packages/keras/engine/training.py in _list_functions_for_serialization(self, serialization_cache)
   2810     self.predict_function = None
   2811     self.train_tf_function = None
-> 2812     functions = super(
   2813         Model, self)._list_functions_for_serialization(serialization_cache)
   2814     self.train_function = train_function

~/miniconda3/lib/python3.8/site-packages/keras/engine/base_layer.py in _list_functions_for_serialization(self, serialization_cache)
   3083 
   3084   def _list_functions_for_serialization(self, serialization_cache):
-> 3085     return (self._trackable_saved_model_saver
   3086             .list_functions_for_serialization(serialization_cache))
   3087 

~/miniconda3/lib/python3.8/site-packages/keras/saving/saved_model/base_serialization.py in list_functions_for_serialization(self, serialization_cache)
     91       return {}
     92 
---> 93     fns = self.functions_to_serialize(serialization_cache)
     94 
     95     # The parent AutoTrackable class saves all user-defined tf.functions, and

~/miniconda3/lib/python3.8/site-packages/keras/saving/saved_model/layer_serialization.py in functions_to_serialize(self, serialization_cache)
     71 
     72   def functions_to_serialize(self, serialization_cache):
---> 73     return (self._get_serialized_attributes(
     74         serialization_cache).functions_to_serialize)
     75 

~/miniconda3/lib/python3.8/site-packages/keras/saving/saved_model/layer_serialization.py in _get_serialized_attributes(self, serialization_cache)
     87       return serialized_attr
     88 
---> 89     object_dict, function_dict = self._get_serialized_attributes_internal(
     90         serialization_cache)
     91 

~/miniconda3/lib/python3.8/site-packages/keras/saving/saved_model/model_serialization.py in _get_serialized_attributes_internal(self, serialization_cache)
     49     # cache (i.e. this is the root level object).
     50     if len(serialization_cache[constants.KERAS_CACHE_KEY]) == 1:
---> 51       default_signature = save_impl.default_save_signature(self.obj)
     52 
     53     # Other than the default signature function, all other attributes match with

~/miniconda3/lib/python3.8/site-packages/keras/saving/saved_model/save_impl.py in default_save_signature(layer)
    206 def default_save_signature(layer):
    207   original_losses = _reset_layer_losses(layer)
--> 208   fn = saving_utils.trace_model_call(layer)
    209   _restore_layer_losses(original_losses)
    210   return fn

~/miniconda3/lib/python3.8/site-packages/keras/saving/saving_utils.py in trace_model_call(model, input_signature)
    133     return {name: output for name, output in zip(output_names, outputs)}
    134 
--> 135   return _wrapped_model.get_concrete_function(*model_args, **model_kwargs)
    136 
    137 

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in get_concrete_function(self, *args, **kwargs)
   1231   def get_concrete_function(self, *args, **kwargs):
   1232     # Implements GenericFunction.get_concrete_function.
-> 1233     concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
   1234     concrete._garbage_collector.release()  # pylint: disable=protected-access
   1235     return concrete

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in _get_concrete_function_garbage_collected(self, *args, **kwargs)
   1211       if self._stateful_fn is None:
   1212         initializers = []
-> 1213         self._initialize(args, kwargs, add_initializers_to=initializers)
   1214         self._initialize_uninitialized_variables(initializers)
   1215 

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in _initialize(self, args, kwds, add_initializers_to)
    757     self._graph_deleter = FunctionDeleter(self._lifted_initializer_graph)
    758     self._concrete_stateful_fn = (
--> 759         self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
    760             *args, **kwds))
    761 

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _get_concrete_function_internal_garbage_collected(self, *args, **kwargs)
   3064       args, kwargs = None, None
   3065     with self._lock:
-> 3066       graph_function, _ = self._maybe_define_function(args, kwargs)
   3067     return graph_function
   3068 

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _maybe_define_function(self, args, kwargs)
   3461 
   3462           self._function_cache.missed.add(call_context_key)
-> 3463           graph_function = self._create_graph_function(args, kwargs)
   3464           self._function_cache.primary[cache_key] = graph_function
   3465 

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   3296     arg_names = base_arg_names + missing_arg_names
   3297     graph_function = ConcreteFunction(
-> 3298         func_graph_module.func_graph_from_py_func(
   3299             self._name,
   3300             self._python_function,

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes, acd_record_initial_resource_uses)
   1005         _, original_func = tf_decorator.unwrap(python_func)
   1006 
-> 1007       func_outputs = python_func(*func_args, **func_kwargs)
   1008 
   1009       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in wrapped_fn(*args, **kwds)
    666         # the function a weak reference to itself to avoid a reference cycle.
    667         with OptionalXlaContext(compile_with_xla):
--> 668           out = weak_wrapped_fn().__wrapped__(*args, **kwds)
    669         return out
    670 

~/miniconda3/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    992           except Exception as e:  # pylint:disable=broad-except
    993             if hasattr(e, "ag_error_metadata"):
--> 994               raise e.ag_error_metadata.to_exception(e)
    995             else:
    996               raise

ValueError: in user code:

    /home/fg/miniconda3/lib/python3.8/site-packages/keras/saving/saving_utils.py:125 _wrapped_model  *
        outputs = model(*args, **kwargs)
    /home/fg/Documents/doctr/doctr/models/recognition/sar/tensorflow.py:263 call  *
        decoded_features = self.decoder(features, encoded, gt=None if target is None else gt, **kwargs)
    /home/fg/Documents/doctr/doctr/models/recognition/sar/tensorflow.py:129 call  *
        states = self.lstm_decoder.get_initial_state(
    /home/fg/miniconda3/lib/python3.8/site-packages/keras/layers/recurrent.py:113 get_initial_state  **
        initial_states.append(get_initial_state_fn(
    /home/fg/miniconda3/lib/python3.8/site-packages/keras/layers/recurrent.py:2516 get_initial_state
        return list(_generate_zero_filled_state_for_cell(
    /home/fg/miniconda3/lib/python3.8/site-packages/keras/layers/recurrent.py:2998 _generate_zero_filled_state_for_cell
        return _generate_zero_filled_state(batch_size, cell.state_size, dtype)
    /home/fg/miniconda3/lib/python3.8/site-packages/keras/layers/recurrent.py:3004 _generate_zero_filled_state
        raise ValueError(

    ValueError: batch_size and dtype cannot be None while constructing initial state: batch_size=None, dtype=<dtype: 'float32'>
```

**Comment by fg-mindee** [comment]
Overruled by #790
