### ISSUE TITLE
Unable to open file while resuming detection training

### ISSUE THREAD

**Issue by dvivarelli** [mindee/doctr#962]
### Bug description

If i set --resume in the training script 

`python references/detection/train_tensorflow.py /content/drive/MyDrive/training_data/detection/train /content/drive/MyDrive/training_data/detection/test linknet_resnet18_rotation  --resume /content/drive/MyDrive/doctr/test-5/checkpoint --batch_size 12 --epochs 300 --rotation --find-lr --wb --name test-5 
`

I receive the following error:
```
Traceback (most recent call last):
  File "references/detection/train_tensorflow.py", line 366, in <module>
    main(args)
  File "references/detection/train_tensorflow.py", line 186, in main
    model.load_weights(args.resume)
  File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 2354, in load_weights
    with h5py.File(filepath, 'r') as f:
  File "/usr/local/lib/python3.7/dist-packages/h5py/_hl/files.py", line 427, in __init__
    swmr=swmr)
  File "/usr/local/lib/python3.7/dist-packages/h5py/_hl/files.py", line 190, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
```

### Code snippet to reproduce the bug

`python references/detection/train_tensorflow.py /content/drive/MyDrive/training_data/detection/train /content/drive/MyDrive/training_data/detection/test linknet_resnet18_rotation  --resume /content/drive/MyDrive/doctr/id-detection-5/checkpoint --batch_size 12 --epochs 300 --rotation --find-lr --wb --name id-detection-5 
`

### Error traceback

```
Traceback (most recent call last):
  File "references/detection/train_tensorflow.py", line 366, in <module>
    main(args)
  File "references/detection/train_tensorflow.py", line 186, in main
    model.load_weights(args.resume)
  File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 2354, in load_weights
    with h5py.File(filepath, 'r') as f:
  File "/usr/local/lib/python3.7/dist-packages/h5py/_hl/files.py", line 427, in __init__
    swmr=swmr)
  File "/usr/local/lib/python3.7/dist-packages/h5py/_hl/files.py", line 190, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
```

### Environment

Colab environment:

DocTR version: 0.6.0a0
TensorFlow version: 2.6.5
PyTorch version: 1.11.0+cu113 (torchvision 0.12.0+cu113)
OpenCV version: 4.1.2
OS: Ubuntu 18.04.5 LTS
Python version: 3.7.13
Is CUDA available (TensorFlow): Yes
Is CUDA available (PyTorch): Yes
CUDA runtime version: 11.1.105
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5

### Deep Learning backend

tensorflow

**Comment by felixdittrich92** [comment]
Hi @dvivarelli , you need to pass the path to weights in TF so add /weights to your resume path :)

**Comment by dvivarelli** [comment]
it's working
Thanks for your help
