### ISSUE TITLE
Train orientation classifier on colab

### ISSUE THREAD

**Issue by synbrAInMircoPiccoli** [mindee/doctr#989]
### Bug description

I have cloned doctr repo, and installed requirements using:

`!git clone https://github.com/mindee/doctr.git
%cd /content/doctr/
!pip install -e . --upgrade
!pip install -r references/requirements.txt
`
and restarted the runtime at the end of installation;
but when i start the training i got the following error:

```
%cd /content/doctr
!python references/classification/train_tensorflow.py mobilenet_v3_large --vocab legacy_french --pretrained --wb --epochs 300 --font "/content/drive/MyDrive/fonts/arial.ttf","/content/drive/MyDrive/fonts/PublicSans-Medium.ttf","/content/drive/MyDrive/fonts/JMH Typewriter.ttf","/content/drive/MyDrive/fonts/FontsFree-Net-ProtraktGX.ttf","/content/drive/MyDrive/fonts/Antiqua Caps Regular.ttf"

/content/doctr
Traceback (most recent call last):
  File "references/classification/train_tensorflow.py", line 21, in <module>
    from doctr.models import login_to_hub, push_to_hf_hub
**ModuleNotFoundError: No module named 'doctr'**
```
### Code snippet to reproduce the bug

---

### Error traceback

```
Traceback (most recent call last):
  File "references/classification/train_tensorflow.py", line 21, in <module>
    from doctr.models import login_to_hub, push_to_hf_hub
ModuleNotFoundError: No module named 'doctr'
```

### Environment

colab env

Collecting environment information...
```
DocTR version: N/A
TensorFlow version: 2.8.2
PyTorch version: 1.12.0+cu113 (torchvision 0.13.0+cu113)
OpenCV version: 4.1.2
OS: Ubuntu 18.04.5 LTS
Python version: 3.7.13
Is CUDA available (TensorFlow): Yes
Is CUDA available (PyTorch): Yes
CUDA runtime version: 11.1.105
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
```
### Deep Learning backend

tensorflow

**Comment by frgfm** [comment]
Hello @synbrAInMircoPiccoli :wave: 

From the information you shared, I guess that the issue is about installing a python lib in Colab (and not specifically with docTR). Did you try to restart your runtime?

You seem to have solved your problem though, could you share how you managed that? :) 

Thanks in advance :v:
